// src/main/webapp/app/entities/request-attribute-value/request-attribute-value-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IRequestAttributeValue, RequestAttributeValue } from 'app/shared/model/request-attribute-value.model';
import { RequestAttributeValueService } from './request-attribute-value.service';
import { IRequestAttribute } from 'app/shared/model/request-attribute.model';
import { RequestAttributeService } from 'app/entities/request-attribute/request-attribute.service';

@Component({
  selector: 'jhi-request-attribute-value-update',
  templateUrl: './request-attribute-value-update.component.html'
})
export class RequestAttributeValueUpdateComponent implements OnInit {
  isSaving: boolean;

  requestattributes: IRequestAttribute[];

  editForm = this.fb.group({
    id: [],
    attributeValue: [null, [Validators.required]],
    reqAttr: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected requestAttributeValueService: RequestAttributeValueService,
    protected requestAttributeService: RequestAttributeService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ requestAttributeValue }) => {
      this.updateForm(requestAttributeValue);
    });
    this.requestAttributeService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IRequestAttribute[]>) => mayBeOk.ok),
        map((response: HttpResponse<IRequestAttribute[]>) => response.body)
      )
      .subscribe((res: IRequestAttribute[]) => (this.requestattributes = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(requestAttributeValue: IRequestAttributeValue) {
    this.editForm.patchValue({
      id: requestAttributeValue.id,
      attributeValue: requestAttributeValue.attributeValue,
      reqAttr: requestAttributeValue.reqAttr
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const requestAttributeValue = this.createFromForm();
    if (requestAttributeValue.id !== undefined) {
      this.subscribeToSaveResponse(this.requestAttributeValueService.update(requestAttributeValue));
    } else {
      this.subscribeToSaveResponse(this.requestAttributeValueService.create(requestAttributeValue));
    }
  }

  private createFromForm(): IRequestAttributeValue {
    return {
      ...new RequestAttributeValue(),
      id: this.editForm.get(['id']).value,
      attributeValue: this.editForm.get(['attributeValue']).value,
      reqAttr: this.editForm.get(['reqAttr']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IRequestAttributeValue>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackRequestAttributeById(index: number, item: IRequestAttribute) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-request-attribute-value-heading" jhiTranslate="ca3SJhApp.requestAttributeValue.home.createOrEditLabel">Create or edit a Request Attribute Value</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.requestAttributeValue.attributeValue" for="field_attributeValue">Attribute Value</label>
                    <input type="text" class="form-control" name="attributeValue" id="field_attributeValue"
                           formControlName="attributeValue"/>
                    <div *ngIf="editForm.get('attributeValue').invalid && (editForm.get('attributeValue').dirty || editForm.get('attributeValue').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('attributeValue').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.requestAttributeValue.reqAttr" for="field_reqAttr">Req Attr</label>
                    <select class="form-control" id="field_reqAttr" name="reqAttr" formControlName="reqAttr">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="requestAttributeOption.id === editForm.get('reqAttr').value?.id ? editForm.get('reqAttr').value : requestAttributeOption" *ngFor="let requestAttributeOption of requestattributes; trackBy: trackRequestAttributeById">{{requestAttributeOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/request-attribute-value/request-attribute-value-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.requestAttributeValue.home.createOrEditLabel" v-text="$t('ca3SApp.requestAttributeValue.home.createOrEditLabel')">Create or edit a RequestAttributeValue</h2>
                <div>
                    <div class="form-group" v-if="requestAttributeValue.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="requestAttributeValue.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.requestAttributeValue.attributeValue')" for="request-attribute-value-attributeValue">Attribute Value</label>
                        <input type="text" class="form-control" name="attributeValue" id="request-attribute-value-attributeValue"
                            :class="{'valid': !$v.requestAttributeValue.attributeValue.$invalid, 'invalid': $v.requestAttributeValue.attributeValue.$invalid }" v-model="$v.requestAttributeValue.attributeValue.$model"  required/>
                        <div v-if="$v.requestAttributeValue.attributeValue.$anyDirty && $v.requestAttributeValue.attributeValue.$invalid">
                            <small class="form-text text-danger" v-if="!$v.requestAttributeValue.attributeValue.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.requestAttributeValue.reqAttr')" for="request-attribute-value-reqAttr">Req Attr</label>
                        <select class="form-control" id="request-attribute-value-reqAttr" name="reqAttr" v-model="requestAttributeValue.reqAttr">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="requestAttributeValue.reqAttr && requestAttributeOption.id === requestAttributeValue.reqAttr.id ? requestAttributeValue.reqAttr : requestAttributeOption" v-for="requestAttributeOption in requestAttributes" :key="requestAttributeOption.id">{{requestAttributeOption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.requestAttributeValue.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./request-attribute-value-update.component.ts">
</script>
