// src/main/webapp/app/entities/rdn/rdn-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.rDN.home.createOrEditLabel" v-text="$t('ca3SApp.rDN.home.createOrEditLabel')">Create or edit a RDN</h2>
                <div>
                    <div class="form-group" v-if="rDN.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="rDN.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.rDN.csr')" for="rdn-csr">Csr</label>
                        <select class="form-control" id="rdn-csr" name="csr" v-model="rDN.csr">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="rDN.csr && cSROption.id === rDN.csr.id ? rDN.csr : cSROption" v-for="cSROption in cSRS" :key="cSROption.id">{{cSROption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.rDN.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./rdn-update.component.ts">
</script>

// src/main/webapp/app/entities/rdn/rdn-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IRDN, RDN } from 'app/shared/model/rdn.model';
import { RDNService } from './rdn.service';
import { ICSR } from 'app/shared/model/csr.model';
import { CSRService } from 'app/entities/csr/csr.service';

@Component({
  selector: 'jhi-rdn-update',
  templateUrl: './rdn-update.component.html'
})
export class RDNUpdateComponent implements OnInit {
  isSaving: boolean;

  csrs: ICSR[];

  editForm = this.fb.group({
    id: [],
    csr: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected rDNService: RDNService,
    protected cSRService: CSRService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ rDN }) => {
      this.updateForm(rDN);
    });
    this.cSRService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICSR[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICSR[]>) => response.body)
      )
      .subscribe((res: ICSR[]) => (this.csrs = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(rDN: IRDN) {
    this.editForm.patchValue({
      id: rDN.id,
      csr: rDN.csr
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const rDN = this.createFromForm();
    if (rDN.id !== undefined) {
      this.subscribeToSaveResponse(this.rDNService.update(rDN));
    } else {
      this.subscribeToSaveResponse(this.rDNService.create(rDN));
    }
  }

  private createFromForm(): IRDN {
    return {
      ...new RDN(),
      id: this.editForm.get(['id']).value,
      csr: this.editForm.get(['csr']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IRDN>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackCSRById(index: number, item: ICSR) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-rdn-heading" jhiTranslate="ca3SJhApp.rDN.home.createOrEditLabel">Create or edit a RDN</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.rDN.csr" for="field_csr">Csr</label>
                    <select class="form-control" id="field_csr" name="csr" formControlName="csr">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="cSROption.id === editForm.get('csr').value?.id ? editForm.get('csr').value : cSROption" *ngFor="let cSROption of csrs; trackBy: trackCSRById">{{cSROption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
