// src/main/webapp/app/entities/rdn/rdn.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ca3SApp.rDN.home.title')" id="rdn-heading">RDNS</span>
            <router-link :to="{name: 'RDNCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-rdn">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ca3SApp.rDN.home.createLabel')">
                    Create a new RDN
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && rDNS && rDNS.length === 0">
            <span v-text="$t('ca3SApp.rDN.home.notFound')">No rDNS found</span>
        </div>
        <div class="table-responsive" v-if="rDNS && rDNS.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th><span v-text="$t('ca3SApp.rDN.csr')">Csr</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="rDN in rDNS"
                    :key="rDN.id">
                    <td>
                        <router-link :to="{name: 'RDNView', params: {rDNId: rDN.id}}">{{rDN.id}}</router-link>
                    </td>
                    <td>
                        <div v-if="rDN.csr">
                            <router-link :to="{name: 'CSRView', params: {cSRId: rDN.csr.id}}">{{rDN.csr.id}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'RDNView', params: {rDNId: rDN.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'RDNEdit', params: {rDNId: rDN.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(rDN)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ca3SApp.rDN.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-rDN-heading" v-bind:title="$t('ca3SApp.rDN.delete.question')">Are you sure you want to delete this RDN?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-rDN" v-text="$t('entity.action.delete')" v-on:click="removeRDN()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./rdn.component.ts">
</script>

// src/main/webapp/app/entities/rdn/rdn.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IRDN } from 'app/shared/model/rdn.model';
import { AccountService } from 'app/core/auth/account.service';
import { RDNService } from './rdn.service';

@Component({
  selector: 'jhi-rdn',
  templateUrl: './rdn.component.html'
})
export class RDNComponent implements OnInit, OnDestroy {
  rDNS: IRDN[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected rDNService: RDNService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.rDNService
      .query()
      .pipe(
        filter((res: HttpResponse<IRDN[]>) => res.ok),
        map((res: HttpResponse<IRDN[]>) => res.body)
      )
      .subscribe(
        (res: IRDN[]) => {
          this.rDNS = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInRDNS();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IRDN) {
    return item.id;
  }

  registerChangeInRDNS() {
    this.eventSubscriber = this.eventManager.subscribe('rDNListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ca3SJhApp.rDN.home.title">RDNS</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-rdn" [routerLink]="['/rdn/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ca3SJhApp.rDN.home.createLabel">
            Create a new RDN
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="rDNS?.length === 0">
        <span jhiTranslate="ca3SJhApp.rDN.home.notFound">No rDNS found</span>
    </div>
    <div class="table-responsive" *ngIf="rDNS?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ca3SJhApp.rDN.csr">Csr</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let rDN of rDNS ;trackBy: trackId">
                <td><a [routerLink]="['/rdn', rDN.id, 'view' ]">{{rDN.id}}</a></td>
                <td>
                    <div *ngIf="rDN.csr">
                        <a [routerLink]="['/csr', rDN.csr?.id, 'view' ]" >{{rDN.csr?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/rdn', rDN.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/rdn', rDN.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/rdn', { outlets: { popup: rDN.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
