// src/main/webapp/app/entities/certificate-attribute/certificate-attribute-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { ICertificateAttribute, CertificateAttribute } from 'app/shared/model/certificate-attribute.model';
import { CertificateAttributeService } from './certificate-attribute.service';
import { ICertificate } from 'app/shared/model/certificate.model';
import { CertificateService } from 'app/entities/certificate/certificate.service';

@Component({
  selector: 'jhi-certificate-attribute-update',
  templateUrl: './certificate-attribute-update.component.html'
})
export class CertificateAttributeUpdateComponent implements OnInit {
  isSaving: boolean;

  certificates: ICertificate[];

  editForm = this.fb.group({
    id: [],
    name: [null, [Validators.required]],
    value: [],
    certificate: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected certificateAttributeService: CertificateAttributeService,
    protected certificateService: CertificateService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ certificateAttribute }) => {
      this.updateForm(certificateAttribute);
    });
    this.certificateService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICertificate[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICertificate[]>) => response.body)
      )
      .subscribe((res: ICertificate[]) => (this.certificates = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(certificateAttribute: ICertificateAttribute) {
    this.editForm.patchValue({
      id: certificateAttribute.id,
      name: certificateAttribute.name,
      value: certificateAttribute.value,
      certificate: certificateAttribute.certificate
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const certificateAttribute = this.createFromForm();
    if (certificateAttribute.id !== undefined) {
      this.subscribeToSaveResponse(this.certificateAttributeService.update(certificateAttribute));
    } else {
      this.subscribeToSaveResponse(this.certificateAttributeService.create(certificateAttribute));
    }
  }

  private createFromForm(): ICertificateAttribute {
    return {
      ...new CertificateAttribute(),
      id: this.editForm.get(['id']).value,
      name: this.editForm.get(['name']).value,
      value: this.editForm.get(['value']).value,
      certificate: this.editForm.get(['certificate']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICertificateAttribute>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackCertificateById(index: number, item: ICertificate) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-certificate-attribute-heading" jhiTranslate="ca3SJhApp.certificateAttribute.home.createOrEditLabel">Create or edit a Certificate Attribute</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificateAttribute.attributeId" for="field_attributeId">Attribute Id</label>
                    <input type="number" class="form-control" name="attributeId" id="field_attributeId"
                           formControlName="attributeId"/>
                    <div *ngIf="editForm.get('attributeId').invalid && (editForm.get('attributeId').dirty || editForm.get('attributeId').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('attributeId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('attributeId')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificateAttribute.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                           formControlName="name"/>
                    <div *ngIf="editForm.get('name').invalid && (editForm.get('name').dirty || editForm.get('name').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('name').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificateAttribute.value" for="field_value">Value</label>
                    <input type="text" class="form-control" name="value" id="field_value"
                           formControlName="value"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificateAttribute.certificate" for="field_certificate">Certificate</label>
                    <select class="form-control" id="field_certificate" name="certificate" formControlName="certificate">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="certificateOption.id === editForm.get('certificate').value?.id ? editForm.get('certificate').value : certificateOption" *ngFor="let certificateOption of certificates; trackBy: trackCertificateById">{{certificateOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/certificate-attribute/certificate-attribute-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.certificateAttribute.home.createOrEditLabel" v-text="$t('ca3SApp.certificateAttribute.home.createOrEditLabel')">Create or edit a CertificateAttribute</h2>
                <div>
                    <div class="form-group" v-if="certificateAttribute.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="certificateAttribute.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificateAttribute.name')" for="certificate-attribute-name">Name</label>
                        <input type="text" class="form-control" name="name" id="certificate-attribute-name"
                            :class="{'valid': !$v.certificateAttribute.name.$invalid, 'invalid': $v.certificateAttribute.name.$invalid }" v-model="$v.certificateAttribute.name.$model"  required/>
                        <div v-if="$v.certificateAttribute.name.$anyDirty && $v.certificateAttribute.name.$invalid">
                            <small class="form-text text-danger" v-if="!$v.certificateAttribute.name.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificateAttribute.value')" for="certificate-attribute-value">Value</label>
                        <input type="text" class="form-control" name="value" id="certificate-attribute-value"
                            :class="{'valid': !$v.certificateAttribute.value.$invalid, 'invalid': $v.certificateAttribute.value.$invalid }" v-model="$v.certificateAttribute.value.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ca3SApp.certificateAttribute.certificate')" for="certificate-attribute-certificate">Certificate</label>
                        <select class="form-control" id="certificate-attribute-certificate" name="certificate" v-model="certificateAttribute.certificate">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="certificateAttribute.certificate && certificateOption.id === certificateAttribute.certificate.id ? certificateAttribute.certificate : certificateOption" v-for="certificateOption in certificates" :key="certificateOption.id">{{certificateOption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.certificateAttribute.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./certificate-attribute-update.component.ts">
</script>
