// src/main/webapp/app/entities/certificate-attribute/certificate-attribute.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { ICertificateAttribute } from 'app/shared/model/certificate-attribute.model';
import { AccountService } from 'app/core/auth/account.service';
import { CertificateAttributeService } from './certificate-attribute.service';

@Component({
  selector: 'jhi-certificate-attribute',
  templateUrl: './certificate-attribute.component.html'
})
export class CertificateAttributeComponent implements OnInit, OnDestroy {
  certificateAttributes: ICertificateAttribute[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected certificateAttributeService: CertificateAttributeService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.certificateAttributeService
      .query()
      .pipe(
        filter((res: HttpResponse<ICertificateAttribute[]>) => res.ok),
        map((res: HttpResponse<ICertificateAttribute[]>) => res.body)
      )
      .subscribe(
        (res: ICertificateAttribute[]) => {
          this.certificateAttributes = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInCertificateAttributes();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: ICertificateAttribute) {
    return item.id;
  }

  registerChangeInCertificateAttributes() {
    this.eventSubscriber = this.eventManager.subscribe('certificateAttributeListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ca3SJhApp.certificateAttribute.home.title">Certificate Attributes</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-certificate-attribute" [routerLink]="['/certificate-attribute/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ca3SJhApp.certificateAttribute.home.createLabel">
            Create a new Certificate Attribute
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="certificateAttributes?.length === 0">
        <span jhiTranslate="ca3SJhApp.certificateAttribute.home.notFound">No certificateAttributes found</span>
    </div>
    <div class="table-responsive" *ngIf="certificateAttributes?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ca3SJhApp.certificateAttribute.name">Name</span></th>
            <th><span jhiTranslate="ca3SJhApp.certificateAttribute.value">Value</span></th>
            <th><span jhiTranslate="ca3SJhApp.certificateAttribute.certificate">Certificate</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let certificateAttribute of certificateAttributes ;trackBy: trackId">
                <td><a [routerLink]="['/certificate-attribute', certificateAttribute.id, 'view' ]">{{certificateAttribute.id}}</a></td>
                <td>{{certificateAttribute.name}}</td>
                <td>{{certificateAttribute.value}}</td>
                <td>
                    <div *ngIf="certificateAttribute.certificate">
                        <a [routerLink]="['/certificate', certificateAttribute.certificate?.id, 'view' ]" >{{certificateAttribute.certificate?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/certificate-attribute', certificateAttribute.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/certificate-attribute', certificateAttribute.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/certificate-attribute', { outlets: { popup: certificateAttribute.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/certificate-attribute/certificate-attribute.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ca3SApp.certificateAttribute.home.title')" id="certificate-attribute-heading">Certificate Attributes</span>
            <router-link :to="{name: 'CertificateAttributeCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-certificate-attribute">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ca3SApp.certificateAttribute.home.createLabel')">
                    Create a new Certificate Attribute
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && certificateAttributes && certificateAttributes.length === 0">
            <span v-text="$t('ca3SApp.certificateAttribute.home.notFound')">No certificateAttributes found</span>
        </div>
        <div class="table-responsive" v-if="certificateAttributes && certificateAttributes.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th><span v-text="$t('ca3SApp.certificateAttribute.name')">Name</span></th>
                    <th><span v-text="$t('ca3SApp.certificateAttribute.value')">Value</span></th>
                    <th><span v-text="$t('ca3SApp.certificateAttribute.certificate')">Certificate</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="certificateAttribute in certificateAttributes"
                    :key="certificateAttribute.id">
                    <td>
                        <router-link :to="{name: 'CertificateAttributeView', params: {certificateAttributeId: certificateAttribute.id}}">{{certificateAttribute.id}}</router-link>
                    </td>
                    <td>{{certificateAttribute.name}}</td>
                    <td>{{certificateAttribute.value}}</td>
                    <td>
                        <div v-if="certificateAttribute.certificate">
                            <router-link :to="{name: 'CertificateView', params: {certificateId: certificateAttribute.certificate.id}}">{{certificateAttribute.certificate.id}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'CertificateAttributeView', params: {certificateAttributeId: certificateAttribute.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CertificateAttributeEdit', params: {certificateAttributeId: certificateAttribute.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(certificateAttribute)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ca3SApp.certificateAttribute.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-certificateAttribute-heading" v-text="$t('ca3SApp.certificateAttribute.delete.question', {'id': removeId})">Are you sure you want to delete this Certificate Attribute?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-certificateAttribute" v-text="$t('entity.action.delete')" v-on:click="removeCertificateAttribute()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./certificate-attribute.component.ts">
</script>
