// src/main/webapp/app/entities/identifier/identifier-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IIdentifier, Identifier } from 'app/shared/model/identifier.model';
import { IdentifierService } from './identifier.service';
import { IAcmeOrder } from 'app/shared/model/acme-order.model';
import { AcmeOrderService } from 'app/entities/acme-order/acme-order.service';

@Component({
  selector: 'jhi-identifier-update',
  templateUrl: './identifier-update.component.html'
})
export class IdentifierUpdateComponent implements OnInit {
  isSaving: boolean;

  acmeorders: IAcmeOrder[];

  editForm = this.fb.group({
    id: [],
    identifierId: [null, [Validators.required]],
    type: [null, [Validators.required]],
    value: [null, [Validators.required]],
    order: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected identifierService: IdentifierService,
    protected acmeOrderService: AcmeOrderService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ identifier }) => {
      this.updateForm(identifier);
    });
    this.acmeOrderService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IAcmeOrder[]>) => mayBeOk.ok),
        map((response: HttpResponse<IAcmeOrder[]>) => response.body)
      )
      .subscribe((res: IAcmeOrder[]) => (this.acmeorders = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(identifier: IIdentifier) {
    this.editForm.patchValue({
      id: identifier.id,
      identifierId: identifier.identifierId,
      type: identifier.type,
      value: identifier.value,
      order: identifier.order
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const identifier = this.createFromForm();
    if (identifier.id !== undefined) {
      this.subscribeToSaveResponse(this.identifierService.update(identifier));
    } else {
      this.subscribeToSaveResponse(this.identifierService.create(identifier));
    }
  }

  private createFromForm(): IIdentifier {
    return {
      ...new Identifier(),
      id: this.editForm.get(['id']).value,
      identifierId: this.editForm.get(['identifierId']).value,
      type: this.editForm.get(['type']).value,
      value: this.editForm.get(['value']).value,
      order: this.editForm.get(['order']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IIdentifier>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackAcmeOrderById(index: number, item: IAcmeOrder) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-identifier-heading" jhiTranslate="ca3SJhApp.identifier.home.createOrEditLabel">Create or edit a Identifier</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.identifier.identifierId" for="field_identifierId">Identifier Id</label>
                    <input type="number" class="form-control" name="identifierId" id="field_identifierId"
                           formControlName="identifierId"/>
                    <div *ngIf="editForm.get('identifierId').invalid && (editForm.get('identifierId').dirty || editForm.get('identifierId').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('identifierId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('identifierId')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.identifier.type" for="field_type">Type</label>
                    <input type="text" class="form-control" name="type" id="field_type"
                           formControlName="type"/>
                    <div *ngIf="editForm.get('type').invalid && (editForm.get('type').dirty || editForm.get('type').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('type').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.identifier.value" for="field_value">Value</label>
                    <input type="text" class="form-control" name="value" id="field_value"
                           formControlName="value"/>
                    <div *ngIf="editForm.get('value').invalid && (editForm.get('value').dirty || editForm.get('value').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('value').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.identifier.order" for="field_order">Order</label>
                    <select class="form-control" id="field_order" name="order" formControlName="order">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="acmeOrderOption.id === editForm.get('order').value?.id ? editForm.get('order').value : acmeOrderOption" *ngFor="let acmeOrderOption of acmeorders; trackBy: trackAcmeOrderById">{{acmeOrderOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/identifier/identifier-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.identifier.home.createOrEditLabel" v-text="$t('ca3SApp.identifier.home.createOrEditLabel')">Create or edit a Identifier</h2>
                <div>
                    <div class="form-group" v-if="identifier.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="identifier.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.identifier.identifierId')" for="identifier-identifierId">Identifier Id</label>
                        <input type="number" class="form-control" name="identifierId" id="identifier-identifierId"
                            :class="{'valid': !$v.identifier.identifierId.$invalid, 'invalid': $v.identifier.identifierId.$invalid }" v-model.number="$v.identifier.identifierId.$model"  required/>
                        <div v-if="$v.identifier.identifierId.$anyDirty && $v.identifier.identifierId.$invalid">
                            <small class="form-text text-danger" v-if="!$v.identifier.identifierId.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.identifier.identifierId.number" v-text="$t('entity.validation.number')">
                                This field should be a number.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.identifier.type')" for="identifier-type">Type</label>
                        <input type="text" class="form-control" name="type" id="identifier-type"
                            :class="{'valid': !$v.identifier.type.$invalid, 'invalid': $v.identifier.type.$invalid }" v-model="$v.identifier.type.$model"  required/>
                        <div v-if="$v.identifier.type.$anyDirty && $v.identifier.type.$invalid">
                            <small class="form-text text-danger" v-if="!$v.identifier.type.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.identifier.value')" for="identifier-value">Value</label>
                        <input type="text" class="form-control" name="value" id="identifier-value"
                            :class="{'valid': !$v.identifier.value.$invalid, 'invalid': $v.identifier.value.$invalid }" v-model="$v.identifier.value.$model"  required/>
                        <div v-if="$v.identifier.value.$anyDirty && $v.identifier.value.$invalid">
                            <small class="form-text text-danger" v-if="!$v.identifier.value.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ca3SApp.identifier.order')" for="identifier-order">Order</label>
                        <select class="form-control" id="identifier-order" name="order" v-model="identifier.order">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="identifier.order && acmeOrderOption.id === identifier.order.id ? identifier.order : acmeOrderOption" v-for="acmeOrderOption in acmeOrders" :key="acmeOrderOption.id">{{acmeOrderOption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.identifier.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./identifier-update.component.ts">
</script>
