// src/main/webapp/app/entities/certificate/certificate.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpHeaders, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiParseLinks, JhiAlertService, JhiDataUtils } from 'ng-jhipster';

import { ICertificate } from 'app/shared/model/certificate.model';
import { AccountService } from 'app/core/auth/account.service';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { CertificateService } from './certificate.service';

@Component({
  selector: 'jhi-certificate',
  templateUrl: './certificate.component.html'
})
export class CertificateComponent implements OnInit, OnDestroy {
  certificates: ICertificate[];
  currentAccount: any;
  eventSubscriber: Subscription;
  itemsPerPage: number;
  links: any;
  page: any;
  predicate: any;
  reverse: any;
  totalItems: number;

  constructor(
    protected certificateService: CertificateService,
    protected jhiAlertService: JhiAlertService,
    protected dataUtils: JhiDataUtils,
    protected eventManager: JhiEventManager,
    protected parseLinks: JhiParseLinks,
    protected accountService: AccountService
  ) {
    this.certificates = [];
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.page = 0;
    this.links = {
      last: 0
    };
    this.predicate = 'id';
    this.reverse = true;
  }

  loadAll() {
    this.certificateService
      .query({
        page: this.page,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe(
        (res: HttpResponse<ICertificate[]>) => this.paginateCertificates(res.body, res.headers),
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  reset() {
    this.page = 0;
    this.certificates = [];
    this.loadAll();
  }

  loadPage(page) {
    this.page = page;
    this.loadAll();
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInCertificates();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: ICertificate) {
    return item.id;
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }

  registerChangeInCertificates() {
    this.eventSubscriber = this.eventManager.subscribe('certificateListModification', response => this.reset());
  }

  sort() {
    const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateCertificates(data: ICertificate[], headers: HttpHeaders) {
    this.links = this.parseLinks.parse(headers.get('link'));
    this.totalItems = parseInt(headers.get('X-Total-Count'), 10);
    for (let i = 0; i < data.length; i++) {
      this.certificates.push(data[i]);
    }
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ca3SJhApp.certificate.home.title">Certificates</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-certificate" [routerLink]="['/certificate/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ca3SJhApp.certificate.home.createLabel">
            Create a new Certificate
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="certificates?.length === 0">
        <span jhiTranslate="ca3SJhApp.certificate.home.notFound">No certificates found</span>
    </div>
    <div class="table-responsive" *ngIf="certificates?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="reset.bind(this)">
            <th jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="tbsDigest"><span jhiTranslate="ca3SJhApp.certificate.tbsDigest">Tbs Digest</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="subject"><span jhiTranslate="ca3SJhApp.certificate.subject">Subject</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="issuer"><span jhiTranslate="ca3SJhApp.certificate.issuer">Issuer</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="type"><span jhiTranslate="ca3SJhApp.certificate.type">Type</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="description"><span jhiTranslate="ca3SJhApp.certificate.description">Description</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="subjectKeyIdentifier"><span jhiTranslate="ca3SJhApp.certificate.subjectKeyIdentifier">Subject Key Identifier</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="authorityKeyIdentifier"><span jhiTranslate="ca3SJhApp.certificate.authorityKeyIdentifier">Authority Key Identifier</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="fingerprint"><span jhiTranslate="ca3SJhApp.certificate.fingerprint">Fingerprint</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="serial"><span jhiTranslate="ca3SJhApp.certificate.serial">Serial</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="validFrom"><span jhiTranslate="ca3SJhApp.certificate.validFrom">Valid From</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="validTo"><span jhiTranslate="ca3SJhApp.certificate.validTo">Valid To</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="creationExecutionId"><span jhiTranslate="ca3SJhApp.certificate.creationExecutionId">Creation Execution Id</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="contentAddedAt"><span jhiTranslate="ca3SJhApp.certificate.contentAddedAt">Content Added At</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="revokedSince"><span jhiTranslate="ca3SJhApp.certificate.revokedSince">Revoked Since</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="revocationReason"><span jhiTranslate="ca3SJhApp.certificate.revocationReason">Revocation Reason</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="revoked"><span jhiTranslate="ca3SJhApp.certificate.revoked">Revoked</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="revocationExecutionId"><span jhiTranslate="ca3SJhApp.certificate.revocationExecutionId">Revocation Execution Id</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="content"><span jhiTranslate="ca3SJhApp.certificate.content">Content</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th></th>
            </tr>
            </thead>
            <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
            <tr *ngFor="let certificate of certificates ;trackBy: trackId">
                <td><a [routerLink]="['/certificate', certificate.id, 'view' ]">{{certificate.id}}</a></td>
                <td>{{certificate.tbsDigest}}</td>
                <td>{{certificate.subject}}</td>
                <td>{{certificate.issuer}}</td>
                <td>{{certificate.type}}</td>
                <td>{{certificate.description}}</td>
                <td>{{certificate.subjectKeyIdentifier}}</td>
                <td>{{certificate.authorityKeyIdentifier}}</td>
                <td>{{certificate.fingerprint}}</td>
                <td>{{certificate.serial}}</td>
                <td>{{certificate.validFrom | date:'mediumDate'}}</td>
                <td>{{certificate.validTo | date:'mediumDate'}}</td>
                <td>{{certificate.creationExecutionId}}</td>
                <td>{{certificate.contentAddedAt | date:'mediumDate'}}</td>
                <td>{{certificate.revokedSince | date:'mediumDate'}}</td>
                <td>{{certificate.revocationReason}}</td>
                <td>{{certificate.revoked}}</td>
                <td>{{certificate.revocationExecutionId}}</td>
                <td>{{certificate.content}}</td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/certificate', certificate.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/certificate', certificate.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/certificate', { outlets: { popup: certificate.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/certificate/certificate.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ca3SApp.certificate.home.title')" id="certificate-heading">Certificates</span>
            <router-link :to="{name: 'CertificateCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-certificate">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ca3SApp.certificate.home.createLabel')">
                    Create a new Certificate
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && certificates && certificates.length === 0">
            <span v-text="$t('ca3SApp.certificate.home.notFound')">No certificates found</span>
        </div>
        <div class="table-responsive" v-if="certificates && certificates.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('tbsDigest')"><span v-text="$t('ca3SApp.certificate.tbsDigest')">Tbs Digest</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('subject')"><span v-text="$t('ca3SApp.certificate.subject')">Subject</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('issuer')"><span v-text="$t('ca3SApp.certificate.issuer')">Issuer</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('type')"><span v-text="$t('ca3SApp.certificate.type')">Type</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('description')"><span v-text="$t('ca3SApp.certificate.description')">Description</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('subjectKeyIdentifier')"><span v-text="$t('ca3SApp.certificate.subjectKeyIdentifier')">Subject Key Identifier</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('authorityKeyIdentifier')"><span v-text="$t('ca3SApp.certificate.authorityKeyIdentifier')">Authority Key Identifier</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('fingerprint')"><span v-text="$t('ca3SApp.certificate.fingerprint')">Fingerprint</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('serial')"><span v-text="$t('ca3SApp.certificate.serial')">Serial</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('validFrom')"><span v-text="$t('ca3SApp.certificate.validFrom')">Valid From</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('validTo')"><span v-text="$t('ca3SApp.certificate.validTo')">Valid To</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('creationExecutionId')"><span v-text="$t('ca3SApp.certificate.creationExecutionId')">Creation Execution Id</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('contentAddedAt')"><span v-text="$t('ca3SApp.certificate.contentAddedAt')">Content Added At</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('revokedSince')"><span v-text="$t('ca3SApp.certificate.revokedSince')">Revoked Since</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('revocationReason')"><span v-text="$t('ca3SApp.certificate.revocationReason')">Revocation Reason</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('revoked')"><span v-text="$t('ca3SApp.certificate.revoked')">Revoked</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('revocationExecutionId')"><span v-text="$t('ca3SApp.certificate.revocationExecutionId')">Revocation Execution Id</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('content')"><span v-text="$t('ca3SApp.certificate.content')">Content</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('csr.id')"><span v-text="$t('ca3SApp.certificate.csr')">Csr</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('issuingCertificate.id')"><span v-text="$t('ca3SApp.certificate.issuingCertificate')">Issuing Certificate</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="certificate in certificates"
                    :key="certificate.id">
                    <td>
                        <router-link :to="{name: 'CertificateView', params: {certificateId: certificate.id}}">{{certificate.id}}</router-link>
                    </td>
                    <td>{{certificate.tbsDigest}}</td>
                    <td>{{certificate.subject}}</td>
                    <td>{{certificate.issuer}}</td>
                    <td>{{certificate.type}}</td>
                    <td>{{certificate.description}}</td>
                    <td>{{certificate.subjectKeyIdentifier}}</td>
                    <td>{{certificate.authorityKeyIdentifier}}</td>
                    <td>{{certificate.fingerprint}}</td>
                    <td>{{certificate.serial}}</td>
                    <td>{{certificate.validFrom}}</td>
                    <td>{{certificate.validTo}}</td>
                    <td>{{certificate.creationExecutionId}}</td>
                    <td>{{certificate.contentAddedAt}}</td>
                    <td>{{certificate.revokedSince}}</td>
                    <td>{{certificate.revocationReason}}</td>
                    <td>{{certificate.revoked}}</td>
                    <td>{{certificate.revocationExecutionId}}</td>
                    <td>{{certificate.content}}</td>
                    <td>
                        <div v-if="certificate.csr">
                            <router-link :to="{name: 'CSRView', params: {cSRId: certificate.csr.id}}">{{certificate.csr.id}}</router-link>
                        </div>
                    </td>
                    <td>
                        <div v-if="certificate.issuingCertificate">
                            <router-link :to="{name: 'CertificateView', params: {certificateId: certificate.issuingCertificate.id}}">{{certificate.issuingCertificate.id}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'CertificateView', params: {certificateId: certificate.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CertificateEdit', params: {certificateId: certificate.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(certificate)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ca3SApp.certificate.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-certificate-heading" v-bind:title="$t('ca3SApp.certificate.delete.question')">Are you sure you want to delete this Certificate?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-certificate" v-text="$t('entity.action.delete')" v-on:click="removeCertificate()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./certificate.component.ts">
</script>
