// src/main/webapp/app/entities/certificate/certificate-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import * as moment from 'moment';
import { JhiAlertService, JhiDataUtils } from 'ng-jhipster';
import { ICertificate, Certificate } from 'app/shared/model/certificate.model';
import { CertificateService } from './certificate.service';
import { ICSR } from 'app/shared/model/csr.model';
import { CSRService } from 'app/entities/csr/csr.service';

@Component({
  selector: 'jhi-certificate-update',
  templateUrl: './certificate-update.component.html'
})
export class CertificateUpdateComponent implements OnInit {
  isSaving: boolean;

  csrs: ICSR[];

  certificates: ICertificate[];
  validFromDp: any;
  validToDp: any;
  contentAddedAtDp: any;
  revokedSinceDp: any;

  editForm = this.fb.group({
    id: [],
    tbsDigest: [null, [Validators.required]],
    subject: [null, [Validators.required]],
    issuer: [null, [Validators.required]],
    type: [null, [Validators.required]],
    description: [],
    subjectKeyIdentifier: [],
    authorityKeyIdentifier: [],
    fingerprint: [],
    serial: [null, [Validators.required]],
    validFrom: [null, [Validators.required]],
    validTo: [null, [Validators.required]],
    creationExecutionId: [],
    contentAddedAt: [],
    revokedSince: [],
    revocationReason: [],
    revoked: [],
    revocationExecutionId: [],
    content: [null, [Validators.required]],
    csr: [],
    issuingCertificate: []
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected jhiAlertService: JhiAlertService,
    protected certificateService: CertificateService,
    protected cSRService: CSRService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ certificate }) => {
      this.updateForm(certificate);
    });
    this.cSRService
      .query({ filter: 'certificate-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<ICSR[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICSR[]>) => response.body)
      )
      .subscribe(
        (res: ICSR[]) => {
          if (!this.editForm.get('csr').value || !this.editForm.get('csr').value.id) {
            this.csrs = res;
          } else {
            this.cSRService
              .find(this.editForm.get('csr').value.id)
              .pipe(
                filter((subResMayBeOk: HttpResponse<ICSR>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<ICSR>) => subResponse.body)
              )
              .subscribe((subRes: ICSR) => (this.csrs = [subRes].concat(res)), (subRes: HttpErrorResponse) => this.onError(subRes.message));
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.certificateService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICertificate[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICertificate[]>) => response.body)
      )
      .subscribe((res: ICertificate[]) => (this.certificates = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(certificate: ICertificate) {
    this.editForm.patchValue({
      id: certificate.id,
      tbsDigest: certificate.tbsDigest,
      subject: certificate.subject,
      issuer: certificate.issuer,
      type: certificate.type,
      description: certificate.description,
      subjectKeyIdentifier: certificate.subjectKeyIdentifier,
      authorityKeyIdentifier: certificate.authorityKeyIdentifier,
      fingerprint: certificate.fingerprint,
      serial: certificate.serial,
      validFrom: certificate.validFrom,
      validTo: certificate.validTo,
      creationExecutionId: certificate.creationExecutionId,
      contentAddedAt: certificate.contentAddedAt,
      revokedSince: certificate.revokedSince,
      revocationReason: certificate.revocationReason,
      revoked: certificate.revoked,
      revocationExecutionId: certificate.revocationExecutionId,
      content: certificate.content,
      csr: certificate.csr,
      issuingCertificate: certificate.issuingCertificate
    });
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }

  setFileData(event, field: string, isImage) {
    return new Promise((resolve, reject) => {
      if (event && event.target && event.target.files && event.target.files[0]) {
        const file: File = event.target.files[0];
        if (isImage && !file.type.startsWith('image/')) {
          reject(`File was expected to be an image but was found to be ${file.type}`);
        } else {
          const filedContentType: string = field + 'ContentType';
          this.dataUtils.toBase64(file, base64Data => {
            this.editForm.patchValue({
              [field]: base64Data,
              [filedContentType]: file.type
            });
          });
        }
      } else {
        reject(`Base64 data was not set as file could not be extracted from passed parameter: ${event}`);
      }
    }).then(
      // eslint-disable-next-line no-console
      () => console.log('blob added'), // success
      this.onError
    );
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const certificate = this.createFromForm();
    if (certificate.id !== undefined) {
      this.subscribeToSaveResponse(this.certificateService.update(certificate));
    } else {
      this.subscribeToSaveResponse(this.certificateService.create(certificate));
    }
  }

  private createFromForm(): ICertificate {
    return {
      ...new Certificate(),
      id: this.editForm.get(['id']).value,
      tbsDigest: this.editForm.get(['tbsDigest']).value,
      subject: this.editForm.get(['subject']).value,
      issuer: this.editForm.get(['issuer']).value,
      type: this.editForm.get(['type']).value,
      description: this.editForm.get(['description']).value,
      subjectKeyIdentifier: this.editForm.get(['subjectKeyIdentifier']).value,
      authorityKeyIdentifier: this.editForm.get(['authorityKeyIdentifier']).value,
      fingerprint: this.editForm.get(['fingerprint']).value,
      serial: this.editForm.get(['serial']).value,
      validFrom: this.editForm.get(['validFrom']).value,
      validTo: this.editForm.get(['validTo']).value,
      creationExecutionId: this.editForm.get(['creationExecutionId']).value,
      contentAddedAt: this.editForm.get(['contentAddedAt']).value,
      revokedSince: this.editForm.get(['revokedSince']).value,
      revocationReason: this.editForm.get(['revocationReason']).value,
      revoked: this.editForm.get(['revoked']).value,
      revocationExecutionId: this.editForm.get(['revocationExecutionId']).value,
      content: this.editForm.get(['content']).value,
      csr: this.editForm.get(['csr']).value,
      issuingCertificate: this.editForm.get(['issuingCertificate']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICertificate>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackCSRById(index: number, item: ICSR) {
    return item.id;
  }

  trackCertificateById(index: number, item: ICertificate) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-certificate-heading" jhiTranslate="ca3SJhApp.certificate.home.createOrEditLabel">Create or edit a Certificate</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.tbsDigest" for="field_tbsDigest">Tbs Digest</label>
                    <input type="text" class="form-control" name="tbsDigest" id="field_tbsDigest"
                           formControlName="tbsDigest"/>
                    <div *ngIf="editForm.get('tbsDigest').invalid && (editForm.get('tbsDigest').dirty || editForm.get('tbsDigest').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('tbsDigest').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.subject" for="field_subject">Subject</label>
                    <input type="text" class="form-control" name="subject" id="field_subject"
                           formControlName="subject"/>
                    <div *ngIf="editForm.get('subject').invalid && (editForm.get('subject').dirty || editForm.get('subject').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('subject').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.issuer" for="field_issuer">Issuer</label>
                    <input type="text" class="form-control" name="issuer" id="field_issuer"
                           formControlName="issuer"/>
                    <div *ngIf="editForm.get('issuer').invalid && (editForm.get('issuer').dirty || editForm.get('issuer').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('issuer').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.type" for="field_type">Type</label>
                    <input type="text" class="form-control" name="type" id="field_type"
                           formControlName="type"/>
                    <div *ngIf="editForm.get('type').invalid && (editForm.get('type').dirty || editForm.get('type').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('type').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.description" for="field_description">Description</label>
                    <input type="text" class="form-control" name="description" id="field_description"
                           formControlName="description"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.subjectKeyIdentifier" for="field_subjectKeyIdentifier">Subject Key Identifier</label>
                    <input type="text" class="form-control" name="subjectKeyIdentifier" id="field_subjectKeyIdentifier"
                           formControlName="subjectKeyIdentifier"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.authorityKeyIdentifier" for="field_authorityKeyIdentifier">Authority Key Identifier</label>
                    <input type="text" class="form-control" name="authorityKeyIdentifier" id="field_authorityKeyIdentifier"
                           formControlName="authorityKeyIdentifier"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.fingerprint" for="field_fingerprint">Fingerprint</label>
                    <input type="text" class="form-control" name="fingerprint" id="field_fingerprint"
                           formControlName="fingerprint"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.serial" for="field_serial">Serial</label>
                    <input type="text" class="form-control" name="serial" id="field_serial"
                           formControlName="serial"/>
                    <div *ngIf="editForm.get('serial').invalid && (editForm.get('serial').dirty || editForm.get('serial').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('serial').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.validFrom" for="field_validFrom">Valid From</label>
                    <div class="input-group">
                        <input id="field_validFrom" type="text" class="form-control" name="validFrom" ngbDatepicker  #validFromDp="ngbDatepicker" formControlName="validFrom"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="validFromDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                    <div *ngIf="editForm.get('validFrom').invalid && (editForm.get('validFrom').dirty || editForm.get('validFrom').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('validFrom').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.validTo" for="field_validTo">Valid To</label>
                    <div class="input-group">
                        <input id="field_validTo" type="text" class="form-control" name="validTo" ngbDatepicker  #validToDp="ngbDatepicker" formControlName="validTo"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="validToDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                    <div *ngIf="editForm.get('validTo').invalid && (editForm.get('validTo').dirty || editForm.get('validTo').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('validTo').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.creationExecutionId" for="field_creationExecutionId">Creation Execution Id</label>
                    <input type="text" class="form-control" name="creationExecutionId" id="field_creationExecutionId"
                           formControlName="creationExecutionId"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.contentAddedAt" for="field_contentAddedAt">Content Added At</label>
                    <div class="input-group">
                        <input id="field_contentAddedAt" type="text" class="form-control" name="contentAddedAt" ngbDatepicker  #contentAddedAtDp="ngbDatepicker" formControlName="contentAddedAt"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="contentAddedAtDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.revokedSince" for="field_revokedSince">Revoked Since</label>
                    <div class="input-group">
                        <input id="field_revokedSince" type="text" class="form-control" name="revokedSince" ngbDatepicker  #revokedSinceDp="ngbDatepicker" formControlName="revokedSince"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="revokedSinceDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.revocationReason" for="field_revocationReason">Revocation Reason</label>
                    <input type="text" class="form-control" name="revocationReason" id="field_revocationReason"
                           formControlName="revocationReason"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.revoked" for="field_revoked">Revoked</label>
                    <input type="checkbox" class="form-control" name="revoked" id="field_revoked"
                           formControlName="revoked"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.revocationExecutionId" for="field_revocationExecutionId">Revocation Execution Id</label>
                    <input type="text" class="form-control" name="revocationExecutionId" id="field_revocationExecutionId"
                           formControlName="revocationExecutionId"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.content" for="field_content">Content</label>
                    <textarea class="form-control" name="content" id="field_content"
                              formControlName="content"></textarea>
                    <div *ngIf="editForm.get('content').invalid && (editForm.get('content').dirty || editForm.get('content').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('content').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.csr" for="field_csr">Csr</label>
                    <select class="form-control" id="field_csr" name="csr" formControlName="csr">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="cSROption.id === editForm.get('csr').value?.id ? editForm.get('csr').value : cSROption" *ngFor="let cSROption of csrs; trackBy: trackCSRById">{{cSROption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.certificate.issuingCertificate" for="field_issuingCertificate">Issuing Certificate</label>
                    <select class="form-control" id="field_issuingCertificate" name="issuingCertificate" formControlName="issuingCertificate">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="certificateOption.id === editForm.get('issuingCertificate').value?.id ? editForm.get('issuingCertificate').value : certificateOption" *ngFor="let certificateOption of certificates; trackBy: trackCertificateById">{{certificateOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/certificate/certificate-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.certificate.home.createOrEditLabel" v-text="$t('ca3SApp.certificate.home.createOrEditLabel')">Create or edit a Certificate</h2>
                <div>
                    <div class="form-group" v-if="certificate.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="certificate.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.tbsDigest')" for="certificate-tbsDigest">Tbs Digest</label>
                        <input type="text" class="form-control" name="tbsDigest" id="certificate-tbsDigest"
                            :class="{'valid': !$v.certificate.tbsDigest.$invalid, 'invalid': $v.certificate.tbsDigest.$invalid }" v-model="$v.certificate.tbsDigest.$model"  required/>
                        <div v-if="$v.certificate.tbsDigest.$anyDirty && $v.certificate.tbsDigest.$invalid">
                            <small class="form-text text-danger" v-if="!$v.certificate.tbsDigest.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.subject')" for="certificate-subject">Subject</label>
                        <input type="text" class="form-control" name="subject" id="certificate-subject"
                            :class="{'valid': !$v.certificate.subject.$invalid, 'invalid': $v.certificate.subject.$invalid }" v-model="$v.certificate.subject.$model"  required/>
                        <div v-if="$v.certificate.subject.$anyDirty && $v.certificate.subject.$invalid">
                            <small class="form-text text-danger" v-if="!$v.certificate.subject.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.issuer')" for="certificate-issuer">Issuer</label>
                        <input type="text" class="form-control" name="issuer" id="certificate-issuer"
                            :class="{'valid': !$v.certificate.issuer.$invalid, 'invalid': $v.certificate.issuer.$invalid }" v-model="$v.certificate.issuer.$model"  required/>
                        <div v-if="$v.certificate.issuer.$anyDirty && $v.certificate.issuer.$invalid">
                            <small class="form-text text-danger" v-if="!$v.certificate.issuer.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.type')" for="certificate-type">Type</label>
                        <input type="text" class="form-control" name="type" id="certificate-type"
                            :class="{'valid': !$v.certificate.type.$invalid, 'invalid': $v.certificate.type.$invalid }" v-model="$v.certificate.type.$model"  required/>
                        <div v-if="$v.certificate.type.$anyDirty && $v.certificate.type.$invalid">
                            <small class="form-text text-danger" v-if="!$v.certificate.type.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.description')" for="certificate-description">Description</label>
                        <input type="text" class="form-control" name="description" id="certificate-description"
                            :class="{'valid': !$v.certificate.description.$invalid, 'invalid': $v.certificate.description.$invalid }" v-model="$v.certificate.description.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.subjectKeyIdentifier')" for="certificate-subjectKeyIdentifier">Subject Key Identifier</label>
                        <input type="text" class="form-control" name="subjectKeyIdentifier" id="certificate-subjectKeyIdentifier"
                            :class="{'valid': !$v.certificate.subjectKeyIdentifier.$invalid, 'invalid': $v.certificate.subjectKeyIdentifier.$invalid }" v-model="$v.certificate.subjectKeyIdentifier.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.authorityKeyIdentifier')" for="certificate-authorityKeyIdentifier">Authority Key Identifier</label>
                        <input type="text" class="form-control" name="authorityKeyIdentifier" id="certificate-authorityKeyIdentifier"
                            :class="{'valid': !$v.certificate.authorityKeyIdentifier.$invalid, 'invalid': $v.certificate.authorityKeyIdentifier.$invalid }" v-model="$v.certificate.authorityKeyIdentifier.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.fingerprint')" for="certificate-fingerprint">Fingerprint</label>
                        <input type="text" class="form-control" name="fingerprint" id="certificate-fingerprint"
                            :class="{'valid': !$v.certificate.fingerprint.$invalid, 'invalid': $v.certificate.fingerprint.$invalid }" v-model="$v.certificate.fingerprint.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.serial')" for="certificate-serial">Serial</label>
                        <input type="text" class="form-control" name="serial" id="certificate-serial"
                            :class="{'valid': !$v.certificate.serial.$invalid, 'invalid': $v.certificate.serial.$invalid }" v-model="$v.certificate.serial.$model"  required/>
                        <div v-if="$v.certificate.serial.$anyDirty && $v.certificate.serial.$invalid">
                            <small class="form-text text-danger" v-if="!$v.certificate.serial.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.validFrom')" for="certificate-validFrom">Valid From</label>
                        <div class="input-group">
                            <input id="certificate-validFrom" type="date" class="form-control" name="validFrom"  :class="{'valid': !$v.certificate.validFrom.$invalid, 'invalid': $v.certificate.validFrom.$invalid }"
                            v-model="$v.certificate.validFrom.$model"  required />
                        </div>
                        <div v-if="$v.certificate.validFrom.$anyDirty && $v.certificate.validFrom.$invalid">
                            <small class="form-text text-danger" v-if="!$v.certificate.validFrom.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.validTo')" for="certificate-validTo">Valid To</label>
                        <div class="input-group">
                            <input id="certificate-validTo" type="date" class="form-control" name="validTo"  :class="{'valid': !$v.certificate.validTo.$invalid, 'invalid': $v.certificate.validTo.$invalid }"
                            v-model="$v.certificate.validTo.$model"  required />
                        </div>
                        <div v-if="$v.certificate.validTo.$anyDirty && $v.certificate.validTo.$invalid">
                            <small class="form-text text-danger" v-if="!$v.certificate.validTo.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.creationExecutionId')" for="certificate-creationExecutionId">Creation Execution Id</label>
                        <input type="text" class="form-control" name="creationExecutionId" id="certificate-creationExecutionId"
                            :class="{'valid': !$v.certificate.creationExecutionId.$invalid, 'invalid': $v.certificate.creationExecutionId.$invalid }" v-model="$v.certificate.creationExecutionId.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.contentAddedAt')" for="certificate-contentAddedAt">Content Added At</label>
                        <div class="input-group">
                            <input id="certificate-contentAddedAt" type="date" class="form-control" name="contentAddedAt"  :class="{'valid': !$v.certificate.contentAddedAt.$invalid, 'invalid': $v.certificate.contentAddedAt.$invalid }"
                            v-model="$v.certificate.contentAddedAt.$model"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.revokedSince')" for="certificate-revokedSince">Revoked Since</label>
                        <div class="input-group">
                            <input id="certificate-revokedSince" type="date" class="form-control" name="revokedSince"  :class="{'valid': !$v.certificate.revokedSince.$invalid, 'invalid': $v.certificate.revokedSince.$invalid }"
                            v-model="$v.certificate.revokedSince.$model"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.revocationReason')" for="certificate-revocationReason">Revocation Reason</label>
                        <input type="text" class="form-control" name="revocationReason" id="certificate-revocationReason"
                            :class="{'valid': !$v.certificate.revocationReason.$invalid, 'invalid': $v.certificate.revocationReason.$invalid }" v-model="$v.certificate.revocationReason.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.revoked')" for="certificate-revoked">Revoked</label>
                        <input type="checkbox" class="form-check" name="revoked" id="certificate-revoked"
                            :class="{'valid': !$v.certificate.revoked.$invalid, 'invalid': $v.certificate.revoked.$invalid }" v-model="$v.certificate.revoked.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.revocationExecutionId')" for="certificate-revocationExecutionId">Revocation Execution Id</label>
                        <input type="text" class="form-control" name="revocationExecutionId" id="certificate-revocationExecutionId"
                            :class="{'valid': !$v.certificate.revocationExecutionId.$invalid, 'invalid': $v.certificate.revocationExecutionId.$invalid }" v-model="$v.certificate.revocationExecutionId.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.content')" for="certificate-content">Content</label>
                        <textarea class="form-control" name="content" id="certificate-content"
                            :class="{'valid': !$v.certificate.content.$invalid, 'invalid': $v.certificate.content.$invalid }" v-model="$v.certificate.content.$model"  required></textarea>
                        <div v-if="$v.certificate.content.$anyDirty && $v.certificate.content.$invalid">
                            <small class="form-text text-danger" v-if="!$v.certificate.content.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.certificate.csr')" for="certificate-csr">Csr</label>
                        <select class="form-control" id="certificate-csr" name="csr" v-model="certificate.csr">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="certificate.csr && cSROption.id === certificate.csr.id ? certificate.csr : cSROption" v-for="cSROption in csrs" :key="cSROption.id">{{cSROption.id}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ca3SApp.certificate.issuingCertificate')" for="certificate-issuingCertificate">Issuing Certificate</label>
                        <select class="form-control" id="certificate-issuingCertificate" name="issuingCertificate" v-model="certificate.issuingCertificate">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="certificate.issuingCertificate && certificateOption.id === certificate.issuingCertificate.id ? certificate.issuingCertificate : certificateOption" v-for="certificateOption in certificates" :key="certificateOption.id">{{certificateOption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.certificate.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./certificate-update.component.ts">
</script>
