// src/main/webapp/app/entities/request-attribute/request-attribute-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.requestAttribute.home.createOrEditLabel" v-text="$t('ca3SApp.requestAttribute.home.createOrEditLabel')">Create or edit a RequestAttribute</h2>
                <div>
                    <div class="form-group" v-if="requestAttribute.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="requestAttribute.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.requestAttribute.attributeType')" for="request-attribute-attributeType">Attribute Type</label>
                        <input type="text" class="form-control" name="attributeType" id="request-attribute-attributeType"
                            :class="{'valid': !$v.requestAttribute.attributeType.$invalid, 'invalid': $v.requestAttribute.attributeType.$invalid }" v-model="$v.requestAttribute.attributeType.$model"  required/>
                        <div v-if="$v.requestAttribute.attributeType.$anyDirty && $v.requestAttribute.attributeType.$invalid">
                            <small class="form-text text-danger" v-if="!$v.requestAttribute.attributeType.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.requestAttribute.holdingRequestAttribute')" for="request-attribute-holdingRequestAttribute">Holding Request Attribute</label>
                        <select class="form-control" id="request-attribute-holdingRequestAttribute" name="holdingRequestAttribute" v-model="requestAttribute.holdingRequestAttribute">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="requestAttribute.holdingRequestAttribute && requestAttributeValueOption.id === requestAttribute.holdingRequestAttribute.id ? requestAttribute.holdingRequestAttribute : requestAttributeValueOption" v-for="requestAttributeValueOption in requestAttributeValues" :key="requestAttributeValueOption.id">{{requestAttributeValueOption.id}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.requestAttribute.csr')" for="request-attribute-csr">Csr</label>
                        <select class="form-control" id="request-attribute-csr" name="csr" v-model="requestAttribute.csr">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="requestAttribute.csr && cSROption.id === requestAttribute.csr.id ? requestAttribute.csr : cSROption" v-for="cSROption in cSRS" :key="cSROption.id">{{cSROption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.requestAttribute.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./request-attribute-update.component.ts">
</script>

// src/main/webapp/app/entities/request-attribute/request-attribute-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IRequestAttribute, RequestAttribute } from 'app/shared/model/request-attribute.model';
import { RequestAttributeService } from './request-attribute.service';
import { IRequestAttributeValue } from 'app/shared/model/request-attribute-value.model';
import { RequestAttributeValueService } from 'app/entities/request-attribute-value/request-attribute-value.service';
import { ICSR } from 'app/shared/model/csr.model';
import { CSRService } from 'app/entities/csr/csr.service';

@Component({
  selector: 'jhi-request-attribute-update',
  templateUrl: './request-attribute-update.component.html'
})
export class RequestAttributeUpdateComponent implements OnInit {
  isSaving: boolean;

  requestattributevalues: IRequestAttributeValue[];

  csrs: ICSR[];

  editForm = this.fb.group({
    id: [],
    attributeType: [null, [Validators.required]],
    holdingRequestAttribute: [],
    csr: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected requestAttributeService: RequestAttributeService,
    protected requestAttributeValueService: RequestAttributeValueService,
    protected cSRService: CSRService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ requestAttribute }) => {
      this.updateForm(requestAttribute);
    });
    this.requestAttributeValueService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IRequestAttributeValue[]>) => mayBeOk.ok),
        map((response: HttpResponse<IRequestAttributeValue[]>) => response.body)
      )
      .subscribe(
        (res: IRequestAttributeValue[]) => (this.requestattributevalues = res),
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.cSRService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICSR[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICSR[]>) => response.body)
      )
      .subscribe((res: ICSR[]) => (this.csrs = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(requestAttribute: IRequestAttribute) {
    this.editForm.patchValue({
      id: requestAttribute.id,
      attributeType: requestAttribute.attributeType,
      holdingRequestAttribute: requestAttribute.holdingRequestAttribute,
      csr: requestAttribute.csr
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const requestAttribute = this.createFromForm();
    if (requestAttribute.id !== undefined) {
      this.subscribeToSaveResponse(this.requestAttributeService.update(requestAttribute));
    } else {
      this.subscribeToSaveResponse(this.requestAttributeService.create(requestAttribute));
    }
  }

  private createFromForm(): IRequestAttribute {
    return {
      ...new RequestAttribute(),
      id: this.editForm.get(['id']).value,
      attributeType: this.editForm.get(['attributeType']).value,
      holdingRequestAttribute: this.editForm.get(['holdingRequestAttribute']).value,
      csr: this.editForm.get(['csr']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IRequestAttribute>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackRequestAttributeValueById(index: number, item: IRequestAttributeValue) {
    return item.id;
  }

  trackCSRById(index: number, item: ICSR) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-request-attribute-heading" jhiTranslate="ca3SJhApp.requestAttribute.home.createOrEditLabel">Create or edit a Request Attribute</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.requestAttribute.attributeType" for="field_attributeType">Attribute Type</label>
                    <input type="text" class="form-control" name="attributeType" id="field_attributeType"
                           formControlName="attributeType"/>
                    <div *ngIf="editForm.get('attributeType').invalid && (editForm.get('attributeType').dirty || editForm.get('attributeType').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('attributeType').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.requestAttribute.holdingRequestAttribute" for="field_holdingRequestAttribute">Holding Request Attribute</label>
                    <select class="form-control" id="field_holdingRequestAttribute" name="holdingRequestAttribute" formControlName="holdingRequestAttribute">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="requestAttributeValueOption.id === editForm.get('holdingRequestAttribute').value?.id ? editForm.get('holdingRequestAttribute').value : requestAttributeValueOption" *ngFor="let requestAttributeValueOption of requestattributevalues; trackBy: trackRequestAttributeValueById">{{requestAttributeValueOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.requestAttribute.csr" for="field_csr">Csr</label>
                    <select class="form-control" id="field_csr" name="csr" formControlName="csr">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="cSROption.id === editForm.get('csr').value?.id ? editForm.get('csr').value : cSROption" *ngFor="let cSROption of csrs; trackBy: trackCSRById">{{cSROption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
