// src/main/webapp/app/entities/csr-attribute/csr-attribute.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ca3SApp.csrAttribute.home.title')" id="csr-attribute-heading">Csr Attributes</span>
            <router-link :to="{name: 'CsrAttributeCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-csr-attribute">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ca3SApp.csrAttribute.home.createLabel')">
                    Create a new Csr Attribute
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && csrAttributes && csrAttributes.length === 0">
            <span v-text="$t('ca3SApp.csrAttribute.home.notFound')">No csrAttributes found</span>
        </div>
        <div class="table-responsive" v-if="csrAttributes && csrAttributes.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th><span v-text="$t('ca3SApp.csrAttribute.name')">Name</span></th>
                    <th><span v-text="$t('ca3SApp.csrAttribute.value')">Value</span></th>
                    <th><span v-text="$t('ca3SApp.csrAttribute.csr')">Csr</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="csrAttribute in csrAttributes"
                    :key="csrAttribute.id">
                    <td>
                        <router-link :to="{name: 'CsrAttributeView', params: {csrAttributeId: csrAttribute.id}}">{{csrAttribute.id}}</router-link>
                    </td>
                    <td>{{csrAttribute.name}}</td>
                    <td>{{csrAttribute.value}}</td>
                    <td>
                        <div v-if="csrAttribute.csr">
                            <router-link :to="{name: 'CSRView', params: {cSRId: csrAttribute.csr.id}}">{{csrAttribute.csr.id}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'CsrAttributeView', params: {csrAttributeId: csrAttribute.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CsrAttributeEdit', params: {csrAttributeId: csrAttribute.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(csrAttribute)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ca3SApp.csrAttribute.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-csrAttribute-heading" v-bind:title="$t('ca3SApp.csrAttribute.delete.question')">Are you sure you want to delete this Csr Attribute?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-csrAttribute" v-text="$t('entity.action.delete')" v-on:click="removeCsrAttribute()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./csr-attribute.component.ts">
</script>

// src/main/webapp/app/entities/csr-attribute/csr-attribute.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { ICsrAttribute } from 'app/shared/model/csr-attribute.model';
import { AccountService } from 'app/core/auth/account.service';
import { CsrAttributeService } from './csr-attribute.service';

@Component({
  selector: 'jhi-csr-attribute',
  templateUrl: './csr-attribute.component.html'
})
export class CsrAttributeComponent implements OnInit, OnDestroy {
  csrAttributes: ICsrAttribute[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected csrAttributeService: CsrAttributeService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.csrAttributeService
      .query()
      .pipe(
        filter((res: HttpResponse<ICsrAttribute[]>) => res.ok),
        map((res: HttpResponse<ICsrAttribute[]>) => res.body)
      )
      .subscribe(
        (res: ICsrAttribute[]) => {
          this.csrAttributes = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInCsrAttributes();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: ICsrAttribute) {
    return item.id;
  }

  registerChangeInCsrAttributes() {
    this.eventSubscriber = this.eventManager.subscribe('csrAttributeListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ca3SJhApp.csrAttribute.home.title">Csr Attributes</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-csr-attribute" [routerLink]="['/csr-attribute/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ca3SJhApp.csrAttribute.home.createLabel">
            Create a new Csr Attribute
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="csrAttributes?.length === 0">
        <span jhiTranslate="ca3SJhApp.csrAttribute.home.notFound">No csrAttributes found</span>
    </div>
    <div class="table-responsive" *ngIf="csrAttributes?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ca3SJhApp.csrAttribute.attributeId">Attribute Id</span></th>
            <th><span jhiTranslate="ca3SJhApp.csrAttribute.name">Name</span></th>
            <th><span jhiTranslate="ca3SJhApp.csrAttribute.value">Value</span></th>
            <th><span jhiTranslate="ca3SJhApp.csrAttribute.csr">Csr</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let csrAttribute of csrAttributes ;trackBy: trackId">
                <td><a [routerLink]="['/csr-attribute', csrAttribute.id, 'view' ]">{{csrAttribute.id}}</a></td>
                <td>{{csrAttribute.attributeId}}</td>
                <td>{{csrAttribute.name}}</td>
                <td>{{csrAttribute.value}}</td>
                <td>
                    <div *ngIf="csrAttribute.csr">
                        <a [routerLink]="['/csr', csrAttribute.csr?.id, 'view' ]" >{{csrAttribute.csr?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/csr-attribute', csrAttribute.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/csr-attribute', csrAttribute.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/csr-attribute', { outlets: { popup: csrAttribute.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
