// src/main/webapp/app/entities/csr-attribute/csr-attribute-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.csrAttribute.home.createOrEditLabel" v-text="$t('ca3SApp.csrAttribute.home.createOrEditLabel')">Create or edit a CsrAttribute</h2>
                <div>
                    <div class="form-group" v-if="csrAttribute.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="csrAttribute.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.csrAttribute.name')" for="csr-attribute-name">Name</label>
                        <input type="text" class="form-control" name="name" id="csr-attribute-name"
                            :class="{'valid': !$v.csrAttribute.name.$invalid, 'invalid': $v.csrAttribute.name.$invalid }" v-model="$v.csrAttribute.name.$model"  required/>
                        <div v-if="$v.csrAttribute.name.$anyDirty && $v.csrAttribute.name.$invalid">
                            <small class="form-text text-danger" v-if="!$v.csrAttribute.name.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.csrAttribute.value')" for="csr-attribute-value">Value</label>
                        <input type="text" class="form-control" name="value" id="csr-attribute-value"
                            :class="{'valid': !$v.csrAttribute.value.$invalid, 'invalid': $v.csrAttribute.value.$invalid }" v-model="$v.csrAttribute.value.$model"  required/>
                        <div v-if="$v.csrAttribute.value.$anyDirty && $v.csrAttribute.value.$invalid">
                            <small class="form-text text-danger" v-if="!$v.csrAttribute.value.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ca3SApp.csrAttribute.csr')" for="csr-attribute-csr">Csr</label>
                        <select class="form-control" id="csr-attribute-csr" name="csr" v-model="csrAttribute.csr">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="csrAttribute.csr && cSROption.id === csrAttribute.csr.id ? csrAttribute.csr : cSROption" v-for="cSROption in cSRS" :key="cSROption.id">{{cSROption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.csrAttribute.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./csr-attribute-update.component.ts">
</script>

// src/main/webapp/app/entities/csr-attribute/csr-attribute-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { ICsrAttribute, CsrAttribute } from 'app/shared/model/csr-attribute.model';
import { CsrAttributeService } from './csr-attribute.service';
import { ICSR } from 'app/shared/model/csr.model';
import { CSRService } from 'app/entities/csr/csr.service';

@Component({
  selector: 'jhi-csr-attribute-update',
  templateUrl: './csr-attribute-update.component.html'
})
export class CsrAttributeUpdateComponent implements OnInit {
  isSaving: boolean;

  csrs: ICSR[];

  editForm = this.fb.group({
    id: [],
    name: [null, [Validators.required]],
    value: [null, [Validators.required]],
    csr: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected csrAttributeService: CsrAttributeService,
    protected cSRService: CSRService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ csrAttribute }) => {
      this.updateForm(csrAttribute);
    });
    this.cSRService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICSR[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICSR[]>) => response.body)
      )
      .subscribe((res: ICSR[]) => (this.csrs = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(csrAttribute: ICsrAttribute) {
    this.editForm.patchValue({
      id: csrAttribute.id,
      name: csrAttribute.name,
      value: csrAttribute.value,
      csr: csrAttribute.csr
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const csrAttribute = this.createFromForm();
    if (csrAttribute.id !== undefined) {
      this.subscribeToSaveResponse(this.csrAttributeService.update(csrAttribute));
    } else {
      this.subscribeToSaveResponse(this.csrAttributeService.create(csrAttribute));
    }
  }

  private createFromForm(): ICsrAttribute {
    return {
      ...new CsrAttribute(),
      id: this.editForm.get(['id']).value,
      name: this.editForm.get(['name']).value,
      value: this.editForm.get(['value']).value,
      csr: this.editForm.get(['csr']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICsrAttribute>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackCSRById(index: number, item: ICSR) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-csr-attribute-heading" jhiTranslate="ca3SJhApp.csrAttribute.home.createOrEditLabel">Create or edit a Csr Attribute</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.csrAttribute.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                           formControlName="name"/>
                    <div *ngIf="editForm.get('name').invalid && (editForm.get('name').dirty || editForm.get('name').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('name').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.csrAttribute.value" for="field_value">Value</label>
                    <input type="text" class="form-control" name="value" id="field_value"
                           formControlName="value"/>
                    <div *ngIf="editForm.get('value').invalid && (editForm.get('value').dirty || editForm.get('value').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('value').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.csrAttribute.csr" for="field_csr">Csr</label>
                    <select class="form-control" id="field_csr" name="csr" formControlName="csr">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="cSROption.id === editForm.get('csr').value?.id ? editForm.get('csr').value : cSROption" *ngFor="let cSROption of csrs; trackBy: trackCSRById">{{cSROption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
