// src/main/webapp/app/entities/acme-account/acme-account.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService, JhiDataUtils } from 'ng-jhipster';

import { IACMEAccount } from 'app/shared/model/acme-account.model';
import { AccountService } from 'app/core/auth/account.service';
import { ACMEAccountService } from './acme-account.service';

@Component({
  selector: 'jhi-acme-account',
  templateUrl: './acme-account.component.html'
})
export class ACMEAccountComponent implements OnInit, OnDestroy {
  aCMEAccounts: IACMEAccount[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected aCMEAccountService: ACMEAccountService,
    protected jhiAlertService: JhiAlertService,
    protected dataUtils: JhiDataUtils,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.aCMEAccountService
      .query()
      .pipe(
        filter((res: HttpResponse<IACMEAccount[]>) => res.ok),
        map((res: HttpResponse<IACMEAccount[]>) => res.body)
      )
      .subscribe(
        (res: IACMEAccount[]) => {
          this.aCMEAccounts = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInACMEAccounts();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IACMEAccount) {
    return item.id;
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }

  registerChangeInACMEAccounts() {
    this.eventSubscriber = this.eventManager.subscribe('aCMEAccountListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ca3SJhApp.aCMEAccount.home.title">ACME Accounts</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-acme-account" [routerLink]="['/acme-account/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ca3SJhApp.aCMEAccount.home.createLabel">
            Create a new ACME Account
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="aCMEAccounts?.length === 0">
        <span jhiTranslate="ca3SJhApp.aCMEAccount.home.notFound">No aCMEAccounts found</span>
    </div>
    <div class="table-responsive" *ngIf="aCMEAccounts?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ca3SJhApp.aCMEAccount.accountId">Account Id</span></th>
            <th><span jhiTranslate="ca3SJhApp.aCMEAccount.realm">Realm</span></th>
            <th><span jhiTranslate="ca3SJhApp.aCMEAccount.status">Status</span></th>
            <th><span jhiTranslate="ca3SJhApp.aCMEAccount.termsOfServiceAgreed">Terms Of Service Agreed</span></th>
            <th><span jhiTranslate="ca3SJhApp.aCMEAccount.publicKeyHash">Public Key Hash</span></th>
            <th><span jhiTranslate="ca3SJhApp.aCMEAccount.publicKey">Public Key</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let aCMEAccount of aCMEAccounts ;trackBy: trackId">
                <td><a [routerLink]="['/acme-account', aCMEAccount.id, 'view' ]">{{aCMEAccount.id}}</a></td>
                <td>{{aCMEAccount.accountId}}</td>
                <td>{{aCMEAccount.realm}}</td>
                <td jhiTranslate="{{'ca3SJhApp.AccountStatus.' + aCMEAccount.status}}">{{aCMEAccount.status}}</td>
                <td>{{aCMEAccount.termsOfServiceAgreed}}</td>
                <td>{{aCMEAccount.publicKeyHash}}</td>
                <td>{{aCMEAccount.publicKey}}</td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/acme-account', aCMEAccount.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/acme-account', aCMEAccount.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/acme-account', { outlets: { popup: aCMEAccount.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/acme-account/acme-account.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ca3SApp.aCMEAccount.home.title')" id="acme-account-heading">ACME Accounts</span>
            <router-link :to="{name: 'ACMEAccountCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-acme-account">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ca3SApp.aCMEAccount.home.createLabel')">
                    Create a new ACME Account
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && aCMEAccounts && aCMEAccounts.length === 0">
            <span v-text="$t('ca3SApp.aCMEAccount.home.notFound')">No aCMEAccounts found</span>
        </div>
        <div class="table-responsive" v-if="aCMEAccounts && aCMEAccounts.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th><span v-text="$t('ca3SApp.aCMEAccount.accountId')">Account Id</span></th>
                    <th><span v-text="$t('ca3SApp.aCMEAccount.realm')">Realm</span></th>
                    <th><span v-text="$t('ca3SApp.aCMEAccount.status')">Status</span></th>
                    <th><span v-text="$t('ca3SApp.aCMEAccount.termsOfServiceAgreed')">Terms Of Service Agreed</span></th>
                    <th><span v-text="$t('ca3SApp.aCMEAccount.publicKeyHash')">Public Key Hash</span></th>
                    <th><span v-text="$t('ca3SApp.aCMEAccount.publicKey')">Public Key</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="aCMEAccount in aCMEAccounts"
                    :key="aCMEAccount.id">
                    <td>
                        <router-link :to="{name: 'ACMEAccountView', params: {aCMEAccountId: aCMEAccount.id}}">{{aCMEAccount.id}}</router-link>
                    </td>
                    <td>{{aCMEAccount.accountId}}</td>
                    <td>{{aCMEAccount.realm}}</td>
                    <td v-text="$t('ca3SApp.AccountStatus.' + aCMEAccount.status)">{{aCMEAccount.status}}</td>
                    <td>{{aCMEAccount.termsOfServiceAgreed}}</td>
                    <td>{{aCMEAccount.publicKeyHash}}</td>
                    <td>{{aCMEAccount.publicKey}}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'ACMEAccountView', params: {aCMEAccountId: aCMEAccount.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'ACMEAccountEdit', params: {aCMEAccountId: aCMEAccount.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(aCMEAccount)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ca3SApp.aCMEAccount.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-aCMEAccount-heading" v-text="$t('ca3SApp.aCMEAccount.delete.question', {'id': removeId})">Are you sure you want to delete this ACME Account?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-aCMEAccount" v-text="$t('entity.action.delete')" v-on:click="removeACMEAccount()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./acme-account.component.ts">
</script>
