// src/main/webapp/app/entities/acme-account/acme-account-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.aCMEAccount.home.createOrEditLabel" v-text="$t('ca3SApp.aCMEAccount.home.createOrEditLabel')">Create or edit a AcmeAccount</h2>
                <div>
                    <div class="form-group" v-if="aCMEAccount.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="aCMEAccount.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.aCMEAccount.accountId')" for="acme-account-accountId">Account Id</label>
                        <input type="number" class="form-control" name="accountId" id="acme-account-accountId"
                            :class="{'valid': !$v.aCMEAccount.accountId.$invalid, 'invalid': $v.aCMEAccount.accountId.$invalid }" v-model.number="$v.aCMEAccount.accountId.$model"  required/>
                        <div v-if="$v.aCMEAccount.accountId.$anyDirty && $v.aCMEAccount.accountId.$invalid">
                            <small class="form-text text-danger" v-if="!$v.aCMEAccount.accountId.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.aCMEAccount.accountId.number" v-text="$t('entity.validation.number')">
                                This field should be a number.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.aCMEAccount.realm')" for="acme-account-realm">Realm</label>
                        <input type="text" class="form-control" name="realm" id="acme-account-realm"
                            :class="{'valid': !$v.aCMEAccount.realm.$invalid, 'invalid': $v.aCMEAccount.realm.$invalid }" v-model="$v.aCMEAccount.realm.$model"  required/>
                        <div v-if="$v.aCMEAccount.realm.$anyDirty && $v.aCMEAccount.realm.$invalid">
                            <small class="form-text text-danger" v-if="!$v.aCMEAccount.realm.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.aCMEAccount.status')" for="acme-account-status">Status</label>
                        <select class="form-control" name="status" :class="{'valid': !$v.aCMEAccount.status.$invalid, 'invalid': $v.aCMEAccount.status.$invalid }" v-model="$v.aCMEAccount.status.$model" id="acme-account-status" >
                            <option value="VALID" v-bind:label="$t('ca3SApp.AccountStatus.VALID')">VALID</option>
                            <option value="DEACTIVATED" v-bind:label="$t('ca3SApp.AccountStatus.DEACTIVATED')">DEACTIVATED</option>
                            <option value="REVOKED" v-bind:label="$t('ca3SApp.AccountStatus.REVOKED')">REVOKED</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.aCMEAccount.termsOfServiceAgreed')" for="acme-account-termsOfServiceAgreed">Terms Of Service Agreed</label>
                        <input type="checkbox" class="form-check" name="termsOfServiceAgreed" id="acme-account-termsOfServiceAgreed"
                            :class="{'valid': !$v.aCMEAccount.termsOfServiceAgreed.$invalid, 'invalid': $v.aCMEAccount.termsOfServiceAgreed.$invalid }" v-model="$v.aCMEAccount.termsOfServiceAgreed.$model"  required/>
                        <div v-if="$v.aCMEAccount.termsOfServiceAgreed.$anyDirty && $v.aCMEAccount.termsOfServiceAgreed.$invalid">
                            <small class="form-text text-danger" v-if="!$v.aCMEAccount.termsOfServiceAgreed.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.aCMEAccount.publicKeyHash')" for="acme-account-publicKeyHash">Public Key Hash</label>
                        <input type="text" class="form-control" name="publicKeyHash" id="acme-account-publicKeyHash"
                            :class="{'valid': !$v.aCMEAccount.publicKeyHash.$invalid, 'invalid': $v.aCMEAccount.publicKeyHash.$invalid }" v-model="$v.aCMEAccount.publicKeyHash.$model"  required/>
                        <div v-if="$v.aCMEAccount.publicKeyHash.$anyDirty && $v.aCMEAccount.publicKeyHash.$invalid">
                            <small class="form-text text-danger" v-if="!$v.aCMEAccount.publicKeyHash.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.aCMEAccount.publicKey')" for="acme-account-publicKey">Public Key</label>
                        <textarea class="form-control" name="publicKey" id="acme-account-publicKey"
                            :class="{'valid': !$v.aCMEAccount.publicKey.$invalid, 'invalid': $v.aCMEAccount.publicKey.$invalid }" v-model="$v.aCMEAccount.publicKey.$model"  required></textarea>
                        <div v-if="$v.aCMEAccount.publicKey.$anyDirty && $v.aCMEAccount.publicKey.$invalid">
                            <small class="form-text text-danger" v-if="!$v.aCMEAccount.publicKey.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.aCMEAccount.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./acme-account-update.component.ts">
</script>

// src/main/webapp/app/entities/acme-account/acme-account-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { JhiAlertService, JhiDataUtils } from 'ng-jhipster';
import { IACMEAccount, ACMEAccount } from 'app/shared/model/acme-account.model';
import { ACMEAccountService } from './acme-account.service';

@Component({
  selector: 'jhi-acme-account-update',
  templateUrl: './acme-account-update.component.html'
})
export class ACMEAccountUpdateComponent implements OnInit {
  isSaving: boolean;

  editForm = this.fb.group({
    id: [],
    accountId: [null, [Validators.required]],
    realm: [null, [Validators.required]],
    status: [],
    termsOfServiceAgreed: [null, [Validators.required]],
    publicKeyHash: [null, [Validators.required]],
    publicKey: [null, [Validators.required]]
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected jhiAlertService: JhiAlertService,
    protected aCMEAccountService: ACMEAccountService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ aCMEAccount }) => {
      this.updateForm(aCMEAccount);
    });
  }

  updateForm(aCMEAccount: IACMEAccount) {
    this.editForm.patchValue({
      id: aCMEAccount.id,
      accountId: aCMEAccount.accountId,
      realm: aCMEAccount.realm,
      status: aCMEAccount.status,
      termsOfServiceAgreed: aCMEAccount.termsOfServiceAgreed,
      publicKeyHash: aCMEAccount.publicKeyHash,
      publicKey: aCMEAccount.publicKey
    });
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }

  setFileData(event, field: string, isImage) {
    return new Promise((resolve, reject) => {
      if (event && event.target && event.target.files && event.target.files[0]) {
        const file: File = event.target.files[0];
        if (isImage && !file.type.startsWith('image/')) {
          reject(`File was expected to be an image but was found to be ${file.type}`);
        } else {
          const filedContentType: string = field + 'ContentType';
          this.dataUtils.toBase64(file, base64Data => {
            this.editForm.patchValue({
              [field]: base64Data,
              [filedContentType]: file.type
            });
          });
        }
      } else {
        reject(`Base64 data was not set as file could not be extracted from passed parameter: ${event}`);
      }
    }).then(
      // eslint-disable-next-line no-console
      () => console.log('blob added'), // success
      this.onError
    );
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const aCMEAccount = this.createFromForm();
    if (aCMEAccount.id !== undefined) {
      this.subscribeToSaveResponse(this.aCMEAccountService.update(aCMEAccount));
    } else {
      this.subscribeToSaveResponse(this.aCMEAccountService.create(aCMEAccount));
    }
  }

  private createFromForm(): IACMEAccount {
    return {
      ...new ACMEAccount(),
      id: this.editForm.get(['id']).value,
      accountId: this.editForm.get(['accountId']).value,
      realm: this.editForm.get(['realm']).value,
      status: this.editForm.get(['status']).value,
      termsOfServiceAgreed: this.editForm.get(['termsOfServiceAgreed']).value,
      publicKeyHash: this.editForm.get(['publicKeyHash']).value,
      publicKey: this.editForm.get(['publicKey']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IACMEAccount>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-acme-account-heading" jhiTranslate="ca3SJhApp.aCMEAccount.home.createOrEditLabel">Create or edit a ACME Account</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.aCMEAccount.accountId" for="field_accountId">Account Id</label>
                    <input type="number" class="form-control" name="accountId" id="field_accountId"
                           formControlName="accountId"/>
                    <div *ngIf="editForm.get('accountId').invalid && (editForm.get('accountId').dirty || editForm.get('accountId').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('accountId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('accountId')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.aCMEAccount.realm" for="field_realm">Realm</label>
                    <input type="text" class="form-control" name="realm" id="field_realm"
                           formControlName="realm"/>
                    <div *ngIf="editForm.get('realm').invalid && (editForm.get('realm').dirty || editForm.get('realm').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('realm').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.aCMEAccount.status" for="field_status">Status</label>
                    <select class="form-control" name="status" formControlName="status" id="field_status">
                        <option value="Valid">{{'ca3SJhApp.AccountStatus.Valid' | translate}}</option>
                        <option value="Deactivated">{{'ca3SJhApp.AccountStatus.Deactivated' | translate}}</option>
                        <option value="Revoked">{{'ca3SJhApp.AccountStatus.Revoked' | translate}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.aCMEAccount.termsOfServiceAgreed" for="field_termsOfServiceAgreed">Terms Of Service Agreed</label>
                    <input type="checkbox" class="form-control" name="termsOfServiceAgreed" id="field_termsOfServiceAgreed"
                           formControlName="termsOfServiceAgreed"/>
                    <div *ngIf="editForm.get('termsOfServiceAgreed').invalid && (editForm.get('termsOfServiceAgreed').dirty || editForm.get('termsOfServiceAgreed').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('termsOfServiceAgreed').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.aCMEAccount.publicKeyHash" for="field_publicKeyHash">Public Key Hash</label>
                    <input type="text" class="form-control" name="publicKeyHash" id="field_publicKeyHash"
                           formControlName="publicKeyHash"/>
                    <div *ngIf="editForm.get('publicKeyHash').invalid && (editForm.get('publicKeyHash').dirty || editForm.get('publicKeyHash').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('publicKeyHash').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.aCMEAccount.publicKey" for="field_publicKey">Public Key</label>
                    <textarea class="form-control" name="publicKey" id="field_publicKey"
                              formControlName="publicKey"></textarea>
                    <div *ngIf="editForm.get('publicKey').invalid && (editForm.get('publicKey').dirty || editForm.get('publicKey').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('publicKey').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
