// src/main/webapp/app/entities/csr/csr-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import { JhiAlertService, JhiDataUtils } from 'ng-jhipster';
import { ICSR, CSR } from 'app/shared/model/csr.model';
import { CSRService } from './csr.service';

@Component({
  selector: 'jhi-csr-update',
  templateUrl: './csr-update.component.html'
})
export class CSRUpdateComponent implements OnInit {
  isSaving: boolean;
  requestedOnDp: any;

  editForm = this.fb.group({
    id: [],
    csrBase64: [null, [Validators.required]],
    requestedOn: [null, [Validators.required]],
    status: [null, [Validators.required]],
    processInstanceId: [],
    signingAlgorithm: [],
    isCSRValid: [],
    x509KeySpec: [],
    publicKeyAlgorithm: [],
    publicKeyHash: [],
    subjectPublicKeyInfoBase64: [null, [Validators.required]]
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected jhiAlertService: JhiAlertService,
    protected cSRService: CSRService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ cSR }) => {
      this.updateForm(cSR);
    });
  }

  updateForm(cSR: ICSR) {
    this.editForm.patchValue({
      id: cSR.id,
      csrBase64: cSR.csrBase64,
      requestedOn: cSR.requestedOn,
      status: cSR.status,
      processInstanceId: cSR.processInstanceId,
      signingAlgorithm: cSR.signingAlgorithm,
      isCSRValid: cSR.isCSRValid,
      x509KeySpec: cSR.x509KeySpec,
      publicKeyAlgorithm: cSR.publicKeyAlgorithm,
      publicKeyHash: cSR.publicKeyHash,
      subjectPublicKeyInfoBase64: cSR.subjectPublicKeyInfoBase64
    });
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }

  setFileData(event, field: string, isImage) {
    return new Promise((resolve, reject) => {
      if (event && event.target && event.target.files && event.target.files[0]) {
        const file: File = event.target.files[0];
        if (isImage && !file.type.startsWith('image/')) {
          reject(`File was expected to be an image but was found to be ${file.type}`);
        } else {
          const filedContentType: string = field + 'ContentType';
          this.dataUtils.toBase64(file, base64Data => {
            this.editForm.patchValue({
              [field]: base64Data,
              [filedContentType]: file.type
            });
          });
        }
      } else {
        reject(`Base64 data was not set as file could not be extracted from passed parameter: ${event}`);
      }
    }).then(
      // eslint-disable-next-line no-console
      () => console.log('blob added'), // success
      this.onError
    );
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const cSR = this.createFromForm();
    if (cSR.id !== undefined) {
      this.subscribeToSaveResponse(this.cSRService.update(cSR));
    } else {
      this.subscribeToSaveResponse(this.cSRService.create(cSR));
    }
  }

  private createFromForm(): ICSR {
    return {
      ...new CSR(),
      id: this.editForm.get(['id']).value,
      csrBase64: this.editForm.get(['csrBase64']).value,
      requestedOn: this.editForm.get(['requestedOn']).value,
      status: this.editForm.get(['status']).value,
      processInstanceId: this.editForm.get(['processInstanceId']).value,
      signingAlgorithm: this.editForm.get(['signingAlgorithm']).value,
      isCSRValid: this.editForm.get(['isCSRValid']).value,
      x509KeySpec: this.editForm.get(['x509KeySpec']).value,
      publicKeyAlgorithm: this.editForm.get(['publicKeyAlgorithm']).value,
      publicKeyHash: this.editForm.get(['publicKeyHash']).value,
      subjectPublicKeyInfoBase64: this.editForm.get(['subjectPublicKeyInfoBase64']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICSR>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-csr-heading" jhiTranslate="ca3SJhApp.cSR.home.createOrEditLabel">Create or edit a CSR</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cSR.csrBase64" for="field_csrBase64">Csr Base 64</label>
                    <textarea class="form-control" name="csrBase64" id="field_csrBase64"
                              formControlName="csrBase64"></textarea>
                    <div *ngIf="editForm.get('csrBase64').invalid && (editForm.get('csrBase64').dirty || editForm.get('csrBase64').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('csrBase64').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cSR.requestedOn" for="field_requestedOn">Requested On</label>
                    <div class="input-group">
                        <input id="field_requestedOn" type="text" class="form-control" name="requestedOn" ngbDatepicker  #requestedOnDp="ngbDatepicker" formControlName="requestedOn"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="requestedOnDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                    <div *ngIf="editForm.get('requestedOn').invalid && (editForm.get('requestedOn').dirty || editForm.get('requestedOn').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('requestedOn').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cSR.status" for="field_status">Status</label>
                    <input type="text" class="form-control" name="status" id="field_status"
                           formControlName="status"/>
                    <div *ngIf="editForm.get('status').invalid && (editForm.get('status').dirty || editForm.get('status').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('status').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cSR.processInstanceId" for="field_processInstanceId">Process Instance Id</label>
                    <input type="text" class="form-control" name="processInstanceId" id="field_processInstanceId"
                           formControlName="processInstanceId"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cSR.signingAlgorithm" for="field_signingAlgorithm">Signing Algorithm</label>
                    <input type="text" class="form-control" name="signingAlgorithm" id="field_signingAlgorithm"
                           formControlName="signingAlgorithm"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cSR.isCSRValid" for="field_isCSRValid">Is CSR Valid</label>
                    <input type="checkbox" class="form-control" name="isCSRValid" id="field_isCSRValid"
                           formControlName="isCSRValid"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cSR.x509KeySpec" for="field_x509KeySpec">X 509 Key Spec</label>
                    <input type="text" class="form-control" name="x509KeySpec" id="field_x509KeySpec"
                           formControlName="x509KeySpec"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cSR.publicKeyAlgorithm" for="field_publicKeyAlgorithm">Public Key Algorithm</label>
                    <input type="text" class="form-control" name="publicKeyAlgorithm" id="field_publicKeyAlgorithm"
                           formControlName="publicKeyAlgorithm"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cSR.publicKeyHash" for="field_publicKeyHash">Public Key Hash</label>
                    <input type="text" class="form-control" name="publicKeyHash" id="field_publicKeyHash"
                           formControlName="publicKeyHash"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cSR.subjectPublicKeyInfoBase64" for="field_subjectPublicKeyInfoBase64">Subject Public Key Info Base 64</label>
                    <textarea class="form-control" name="subjectPublicKeyInfoBase64" id="field_subjectPublicKeyInfoBase64"
                              formControlName="subjectPublicKeyInfoBase64"></textarea>
                    <div *ngIf="editForm.get('subjectPublicKeyInfoBase64').invalid && (editForm.get('subjectPublicKeyInfoBase64').dirty || editForm.get('subjectPublicKeyInfoBase64').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('subjectPublicKeyInfoBase64').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/csr/csr-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.cSR.home.createOrEditLabel" v-text="$t('ca3SApp.cSR.home.createOrEditLabel')">Create or edit a CSR</h2>
                <div>
                    <div class="form-group" v-if="cSR.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="cSR.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cSR.csrBase64')" for="csr-csrBase64">Csr Base 64</label>
                        <textarea class="form-control" name="csrBase64" id="csr-csrBase64"
                            :class="{'valid': !$v.cSR.csrBase64.$invalid, 'invalid': $v.cSR.csrBase64.$invalid }" v-model="$v.cSR.csrBase64.$model"  required></textarea>
                        <div v-if="$v.cSR.csrBase64.$anyDirty && $v.cSR.csrBase64.$invalid">
                            <small class="form-text text-danger" v-if="!$v.cSR.csrBase64.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cSR.requestedOn')" for="csr-requestedOn">Requested On</label>
                        <div class="input-group">
                            <input id="csr-requestedOn" type="date" class="form-control" name="requestedOn"  :class="{'valid': !$v.cSR.requestedOn.$invalid, 'invalid': $v.cSR.requestedOn.$invalid }"
                            v-model="$v.cSR.requestedOn.$model"  required />
                        </div>
                        <div v-if="$v.cSR.requestedOn.$anyDirty && $v.cSR.requestedOn.$invalid">
                            <small class="form-text text-danger" v-if="!$v.cSR.requestedOn.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cSR.status')" for="csr-status">Status</label>
                        <select class="form-control" name="status" :class="{'valid': !$v.cSR.status.$invalid, 'invalid': $v.cSR.status.$invalid }" v-model="$v.cSR.status.$model" id="csr-status"  required>
                            <option value="PROCESSING" v-bind:label="$t('ca3SApp.CsrStatus.PROCESSING')">PROCESSING</option>
                            <option value="ISSUED" v-bind:label="$t('ca3SApp.CsrStatus.ISSUED')">ISSUED</option>
                            <option value="REJECTED" v-bind:label="$t('ca3SApp.CsrStatus.REJECTED')">REJECTED</option>
                            <option value="PENDING" v-bind:label="$t('ca3SApp.CsrStatus.PENDING')">PENDING</option>
                        </select>
                        <div v-if="$v.cSR.status.$anyDirty && $v.cSR.status.$invalid">
                            <small class="form-text text-danger" v-if="!$v.cSR.status.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cSR.processInstanceId')" for="csr-processInstanceId">Process Instance Id</label>
                        <input type="text" class="form-control" name="processInstanceId" id="csr-processInstanceId"
                            :class="{'valid': !$v.cSR.processInstanceId.$invalid, 'invalid': $v.cSR.processInstanceId.$invalid }" v-model="$v.cSR.processInstanceId.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cSR.signingAlgorithm')" for="csr-signingAlgorithm">Signing Algorithm</label>
                        <input type="text" class="form-control" name="signingAlgorithm" id="csr-signingAlgorithm"
                            :class="{'valid': !$v.cSR.signingAlgorithm.$invalid, 'invalid': $v.cSR.signingAlgorithm.$invalid }" v-model="$v.cSR.signingAlgorithm.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cSR.isCSRValid')" for="csr-isCSRValid">Is CSR Valid</label>
                        <input type="checkbox" class="form-check" name="isCSRValid" id="csr-isCSRValid"
                            :class="{'valid': !$v.cSR.isCSRValid.$invalid, 'invalid': $v.cSR.isCSRValid.$invalid }" v-model="$v.cSR.isCSRValid.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cSR.x509KeySpec')" for="csr-x509KeySpec">X 509 Key Spec</label>
                        <input type="text" class="form-control" name="x509KeySpec" id="csr-x509KeySpec"
                            :class="{'valid': !$v.cSR.x509KeySpec.$invalid, 'invalid': $v.cSR.x509KeySpec.$invalid }" v-model="$v.cSR.x509KeySpec.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cSR.publicKeyAlgorithm')" for="csr-publicKeyAlgorithm">Public Key Algorithm</label>
                        <input type="text" class="form-control" name="publicKeyAlgorithm" id="csr-publicKeyAlgorithm"
                            :class="{'valid': !$v.cSR.publicKeyAlgorithm.$invalid, 'invalid': $v.cSR.publicKeyAlgorithm.$invalid }" v-model="$v.cSR.publicKeyAlgorithm.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cSR.publicKeyHash')" for="csr-publicKeyHash">Public Key Hash</label>
                        <input type="text" class="form-control" name="publicKeyHash" id="csr-publicKeyHash"
                            :class="{'valid': !$v.cSR.publicKeyHash.$invalid, 'invalid': $v.cSR.publicKeyHash.$invalid }" v-model="$v.cSR.publicKeyHash.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cSR.subjectPublicKeyInfoBase64')" for="csr-subjectPublicKeyInfoBase64">Subject Public Key Info Base 64</label>
                        <textarea class="form-control" name="subjectPublicKeyInfoBase64" id="csr-subjectPublicKeyInfoBase64"
                            :class="{'valid': !$v.cSR.subjectPublicKeyInfoBase64.$invalid, 'invalid': $v.cSR.subjectPublicKeyInfoBase64.$invalid }" v-model="$v.cSR.subjectPublicKeyInfoBase64.$model"  required></textarea>
                        <div v-if="$v.cSR.subjectPublicKeyInfoBase64.$anyDirty && $v.cSR.subjectPublicKeyInfoBase64.$invalid">
                            <small class="form-text text-danger" v-if="!$v.cSR.subjectPublicKeyInfoBase64.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.cSR.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./csr-update.component.ts">
</script>
