// src/main/webapp/app/entities/csr/csr.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ca3SApp.cSR.home.title')" id="csr-heading">CSRS</span>
            <router-link :to="{name: 'CSRCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-csr">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ca3SApp.cSR.home.createLabel')">
                    Create a new CSR
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && cSRS && cSRS.length === 0">
            <span v-text="$t('ca3SApp.cSR.home.notFound')">No cSRS found</span>
        </div>
        <div class="table-responsive" v-if="cSRS && cSRS.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th><span v-text="$t('ca3SApp.cSR.csrBase64')">Csr Base 64</span></th>
                    <th><span v-text="$t('ca3SApp.cSR.requestedOn')">Requested On</span></th>
                    <th><span v-text="$t('ca3SApp.cSR.status')">Status</span></th>
                    <th><span v-text="$t('ca3SApp.cSR.processInstanceId')">Process Instance Id</span></th>
                    <th><span v-text="$t('ca3SApp.cSR.signingAlgorithm')">Signing Algorithm</span></th>
                    <th><span v-text="$t('ca3SApp.cSR.isCSRValid')">Is CSR Valid</span></th>
                    <th><span v-text="$t('ca3SApp.cSR.x509KeySpec')">X 509 Key Spec</span></th>
                    <th><span v-text="$t('ca3SApp.cSR.publicKeyAlgorithm')">Public Key Algorithm</span></th>
                    <th><span v-text="$t('ca3SApp.cSR.publicKeyHash')">Public Key Hash</span></th>
                    <th><span v-text="$t('ca3SApp.cSR.subjectPublicKeyInfoBase64')">Subject Public Key Info Base 64</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="cSR in cSRS"
                    :key="cSR.id">
                    <td>
                        <router-link :to="{name: 'CSRView', params: {cSRId: cSR.id}}">{{cSR.id}}</router-link>
                    </td>
                    <td>{{cSR.csrBase64}}</td>
                    <td>{{cSR.requestedOn}}</td>
                    <td v-text="$t('ca3SApp.CsrStatus.' + cSR.status)">{{cSR.status}}</td>
                    <td>{{cSR.processInstanceId}}</td>
                    <td>{{cSR.signingAlgorithm}}</td>
                    <td>{{cSR.isCSRValid}}</td>
                    <td>{{cSR.x509KeySpec}}</td>
                    <td>{{cSR.publicKeyAlgorithm}}</td>
                    <td>{{cSR.publicKeyHash}}</td>
                    <td>{{cSR.subjectPublicKeyInfoBase64}}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'CSRView', params: {cSRId: cSR.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CSREdit', params: {cSRId: cSR.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(cSR)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ca3SApp.cSR.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-cSR-heading" v-bind:title="$t('ca3SApp.cSR.delete.question')">Are you sure you want to delete this CSR?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-cSR" v-text="$t('entity.action.delete')" v-on:click="removeCSR()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./csr.component.ts">
</script>

// src/main/webapp/app/entities/csr/csr.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService, JhiDataUtils } from 'ng-jhipster';

import { ICSR } from 'app/shared/model/csr.model';
import { AccountService } from 'app/core/auth/account.service';
import { CSRService } from './csr.service';

@Component({
  selector: 'jhi-csr',
  templateUrl: './csr.component.html'
})
export class CSRComponent implements OnInit, OnDestroy {
  cSRS: ICSR[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected cSRService: CSRService,
    protected jhiAlertService: JhiAlertService,
    protected dataUtils: JhiDataUtils,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.cSRService
      .query()
      .pipe(
        filter((res: HttpResponse<ICSR[]>) => res.ok),
        map((res: HttpResponse<ICSR[]>) => res.body)
      )
      .subscribe(
        (res: ICSR[]) => {
          this.cSRS = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInCSRS();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: ICSR) {
    return item.id;
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }

  registerChangeInCSRS() {
    this.eventSubscriber = this.eventManager.subscribe('cSRListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ca3SJhApp.cSR.home.title">CSRS</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-csr" [routerLink]="['/csr/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ca3SJhApp.cSR.home.createLabel">
            Create a new CSR
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="cSRS?.length === 0">
        <span jhiTranslate="ca3SJhApp.cSR.home.notFound">No cSRS found</span>
    </div>
    <div class="table-responsive" *ngIf="cSRS?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ca3SJhApp.cSR.csrBase64">Csr Base 64</span></th>
            <th><span jhiTranslate="ca3SJhApp.cSR.requestedOn">Requested On</span></th>
            <th><span jhiTranslate="ca3SJhApp.cSR.status">Status</span></th>
            <th><span jhiTranslate="ca3SJhApp.cSR.processInstanceId">Process Instance Id</span></th>
            <th><span jhiTranslate="ca3SJhApp.cSR.signingAlgorithm">Signing Algorithm</span></th>
            <th><span jhiTranslate="ca3SJhApp.cSR.isCSRValid">Is CSR Valid</span></th>
            <th><span jhiTranslate="ca3SJhApp.cSR.x509KeySpec">X 509 Key Spec</span></th>
            <th><span jhiTranslate="ca3SJhApp.cSR.publicKeyAlgorithm">Public Key Algorithm</span></th>
            <th><span jhiTranslate="ca3SJhApp.cSR.publicKeyHash">Public Key Hash</span></th>
            <th><span jhiTranslate="ca3SJhApp.cSR.subjectPublicKeyInfoBase64">Subject Public Key Info Base 64</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let cSR of cSRS ;trackBy: trackId">
                <td><a [routerLink]="['/csr', cSR.id, 'view' ]">{{cSR.id}}</a></td>
                <td>{{cSR.csrBase64}}</td>
                <td>{{cSR.requestedOn | date:'mediumDate'}}</td>
                <td>{{cSR.status}}</td>
                <td>{{cSR.processInstanceId}}</td>
                <td>{{cSR.signingAlgorithm}}</td>
                <td>{{cSR.isCSRValid}}</td>
                <td>{{cSR.x509KeySpec}}</td>
                <td>{{cSR.publicKeyAlgorithm}}</td>
                <td>{{cSR.publicKeyHash}}</td>
                <td>{{cSR.subjectPublicKeyInfoBase64}}</td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/csr', cSR.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/csr', cSR.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/csr', { outlets: { popup: cSR.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
