// src/main/webapp/app/entities/rdn-attribute/rdn-attribute-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IRDNAttribute, RDNAttribute } from 'app/shared/model/rdn-attribute.model';
import { RDNAttributeService } from './rdn-attribute.service';
import { IRDN } from 'app/shared/model/rdn.model';
import { RDNService } from 'app/entities/rdn/rdn.service';

@Component({
  selector: 'jhi-rdn-attribute-update',
  templateUrl: './rdn-attribute-update.component.html'
})
export class RDNAttributeUpdateComponent implements OnInit {
  isSaving: boolean;

  rdns: IRDN[];

  editForm = this.fb.group({
    id: [],
    attributeType: [null, [Validators.required]],
    attributeValue: [null, [Validators.required]],
    rdn: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected rDNAttributeService: RDNAttributeService,
    protected rDNService: RDNService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ rDNAttribute }) => {
      this.updateForm(rDNAttribute);
    });
    this.rDNService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IRDN[]>) => mayBeOk.ok),
        map((response: HttpResponse<IRDN[]>) => response.body)
      )
      .subscribe((res: IRDN[]) => (this.rdns = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(rDNAttribute: IRDNAttribute) {
    this.editForm.patchValue({
      id: rDNAttribute.id,
      attributeType: rDNAttribute.attributeType,
      attributeValue: rDNAttribute.attributeValue,
      rdn: rDNAttribute.rdn
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const rDNAttribute = this.createFromForm();
    if (rDNAttribute.id !== undefined) {
      this.subscribeToSaveResponse(this.rDNAttributeService.update(rDNAttribute));
    } else {
      this.subscribeToSaveResponse(this.rDNAttributeService.create(rDNAttribute));
    }
  }

  private createFromForm(): IRDNAttribute {
    return {
      ...new RDNAttribute(),
      id: this.editForm.get(['id']).value,
      attributeType: this.editForm.get(['attributeType']).value,
      attributeValue: this.editForm.get(['attributeValue']).value,
      rdn: this.editForm.get(['rdn']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IRDNAttribute>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackRDNById(index: number, item: IRDN) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-rdn-attribute-heading" jhiTranslate="ca3SJhApp.rDNAttribute.home.createOrEditLabel">Create or edit a RDN Attribute</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.rDNAttribute.attributeType" for="field_attributeType">Attribute Type</label>
                    <input type="text" class="form-control" name="attributeType" id="field_attributeType"
                           formControlName="attributeType"/>
                    <div *ngIf="editForm.get('attributeType').invalid && (editForm.get('attributeType').dirty || editForm.get('attributeType').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('attributeType').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.rDNAttribute.attributeValue" for="field_attributeValue">Attribute Value</label>
                    <input type="text" class="form-control" name="attributeValue" id="field_attributeValue"
                           formControlName="attributeValue"/>
                    <div *ngIf="editForm.get('attributeValue').invalid && (editForm.get('attributeValue').dirty || editForm.get('attributeValue').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('attributeValue').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.rDNAttribute.rdn" for="field_rdn">Rdn</label>
                    <select class="form-control" id="field_rdn" name="rdn" formControlName="rdn">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="rDNOption.id === editForm.get('rdn').value?.id ? editForm.get('rdn').value : rDNOption" *ngFor="let rDNOption of rdns; trackBy: trackRDNById">{{rDNOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/rdn-attribute/rdn-attribute-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.rDNAttribute.home.createOrEditLabel" v-text="$t('ca3SApp.rDNAttribute.home.createOrEditLabel')">Create or edit a RDNAttribute</h2>
                <div>
                    <div class="form-group" v-if="rDNAttribute.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="rDNAttribute.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.rDNAttribute.attributeType')" for="rdn-attribute-attributeType">Attribute Type</label>
                        <input type="text" class="form-control" name="attributeType" id="rdn-attribute-attributeType"
                            :class="{'valid': !$v.rDNAttribute.attributeType.$invalid, 'invalid': $v.rDNAttribute.attributeType.$invalid }" v-model="$v.rDNAttribute.attributeType.$model"  required/>
                        <div v-if="$v.rDNAttribute.attributeType.$anyDirty && $v.rDNAttribute.attributeType.$invalid">
                            <small class="form-text text-danger" v-if="!$v.rDNAttribute.attributeType.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.rDNAttribute.attributeValue')" for="rdn-attribute-attributeValue">Attribute Value</label>
                        <input type="text" class="form-control" name="attributeValue" id="rdn-attribute-attributeValue"
                            :class="{'valid': !$v.rDNAttribute.attributeValue.$invalid, 'invalid': $v.rDNAttribute.attributeValue.$invalid }" v-model="$v.rDNAttribute.attributeValue.$model"  required/>
                        <div v-if="$v.rDNAttribute.attributeValue.$anyDirty && $v.rDNAttribute.attributeValue.$invalid">
                            <small class="form-text text-danger" v-if="!$v.rDNAttribute.attributeValue.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ca3SApp.rDNAttribute.rdn')" for="rdn-attribute-rdn">Rdn</label>
                        <select class="form-control" id="rdn-attribute-rdn" name="rdn" v-model="rDNAttribute.rdn">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="rDNAttribute.rdn && rDNOption.id === rDNAttribute.rdn.id ? rDNAttribute.rdn : rDNOption" v-for="rDNOption in rDNS" :key="rDNOption.id">{{rDNOption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.rDNAttribute.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./rdn-attribute-update.component.ts">
</script>
