// src/main/webapp/app/entities/rdn-attribute/rdn-attribute.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IRDNAttribute } from 'app/shared/model/rdn-attribute.model';
import { AccountService } from 'app/core/auth/account.service';
import { RDNAttributeService } from './rdn-attribute.service';

@Component({
  selector: 'jhi-rdn-attribute',
  templateUrl: './rdn-attribute.component.html'
})
export class RDNAttributeComponent implements OnInit, OnDestroy {
  rDNAttributes: IRDNAttribute[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected rDNAttributeService: RDNAttributeService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.rDNAttributeService
      .query()
      .pipe(
        filter((res: HttpResponse<IRDNAttribute[]>) => res.ok),
        map((res: HttpResponse<IRDNAttribute[]>) => res.body)
      )
      .subscribe(
        (res: IRDNAttribute[]) => {
          this.rDNAttributes = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInRDNAttributes();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IRDNAttribute) {
    return item.id;
  }

  registerChangeInRDNAttributes() {
    this.eventSubscriber = this.eventManager.subscribe('rDNAttributeListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ca3SJhApp.rDNAttribute.home.title">RDN Attributes</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-rdn-attribute" [routerLink]="['/rdn-attribute/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ca3SJhApp.rDNAttribute.home.createLabel">
            Create a new RDN Attribute
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="rDNAttributes?.length === 0">
        <span jhiTranslate="ca3SJhApp.rDNAttribute.home.notFound">No rDNAttributes found</span>
    </div>
    <div class="table-responsive" *ngIf="rDNAttributes?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ca3SJhApp.rDNAttribute.attributeType">Attribute Type</span></th>
            <th><span jhiTranslate="ca3SJhApp.rDNAttribute.attributeValue">Attribute Value</span></th>
            <th><span jhiTranslate="ca3SJhApp.rDNAttribute.rdn">Rdn</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let rDNAttribute of rDNAttributes ;trackBy: trackId">
                <td><a [routerLink]="['/rdn-attribute', rDNAttribute.id, 'view' ]">{{rDNAttribute.id}}</a></td>
                <td>{{rDNAttribute.attributeType}}</td>
                <td>{{rDNAttribute.attributeValue}}</td>
                <td>
                    <div *ngIf="rDNAttribute.rdn">
                        <a [routerLink]="['/rdn', rDNAttribute.rdn?.id, 'view' ]" >{{rDNAttribute.rdn?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/rdn-attribute', rDNAttribute.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/rdn-attribute', rDNAttribute.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/rdn-attribute', { outlets: { popup: rDNAttribute.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/rdn-attribute/rdn-attribute.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ca3SApp.rDNAttribute.home.title')" id="rdn-attribute-heading">RDN Attributes</span>
            <router-link :to="{name: 'RDNAttributeCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-rdn-attribute">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ca3SApp.rDNAttribute.home.createLabel')">
                    Create a new RDN Attribute
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && rDNAttributes && rDNAttributes.length === 0">
            <span v-text="$t('ca3SApp.rDNAttribute.home.notFound')">No rDNAttributes found</span>
        </div>
        <div class="table-responsive" v-if="rDNAttributes && rDNAttributes.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th><span v-text="$t('ca3SApp.rDNAttribute.attributeType')">Attribute Type</span></th>
                    <th><span v-text="$t('ca3SApp.rDNAttribute.attributeValue')">Attribute Value</span></th>
                    <th><span v-text="$t('ca3SApp.rDNAttribute.rdn')">Rdn</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="rDNAttribute in rDNAttributes"
                    :key="rDNAttribute.id">
                    <td>
                        <router-link :to="{name: 'RDNAttributeView', params: {rDNAttributeId: rDNAttribute.id}}">{{rDNAttribute.id}}</router-link>
                    </td>
                    <td>{{rDNAttribute.attributeType}}</td>
                    <td>{{rDNAttribute.attributeValue}}</td>
                    <td>
                        <div v-if="rDNAttribute.rdn">
                            <router-link :to="{name: 'RDNView', params: {rDNId: rDNAttribute.rdn.id}}">{{rDNAttribute.rdn.id}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'RDNAttributeView', params: {rDNAttributeId: rDNAttribute.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'RDNAttributeEdit', params: {rDNAttributeId: rDNAttribute.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(rDNAttribute)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ca3SApp.rDNAttribute.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-rDNAttribute-heading" v-text="$t('ca3SApp.rDNAttribute.delete.question', {'id': removeId})">Are you sure you want to delete this RDN Attribute?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-rDNAttribute" v-text="$t('entity.action.delete')" v-on:click="removeRDNAttribute()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./rdn-attribute.component.ts">
</script>
