// src/main/webapp/app/entities/acme-contact/acme-contact-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.acmeContact.home.createOrEditLabel" v-text="$t('ca3SApp.acmeContact.home.createOrEditLabel')">Create or edit a AcmeContact</h2>
                <div>
                    <div class="form-group" v-if="acmeContact.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="acmeContact.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeContact.contactId')" for="acme-contact-contactId">Contact Id</label>
                        <input type="number" class="form-control" name="contactId" id="acme-contact-contactId"
                            :class="{'valid': !$v.acmeContact.contactId.$invalid, 'invalid': $v.acmeContact.contactId.$invalid }" v-model.number="$v.acmeContact.contactId.$model"  required/>
                        <div v-if="$v.acmeContact.contactId.$anyDirty && $v.acmeContact.contactId.$invalid">
                            <small class="form-text text-danger" v-if="!$v.acmeContact.contactId.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.acmeContact.contactId.number" v-text="$t('entity.validation.number')">
                                This field should be a number.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeContact.contactUrl')" for="acme-contact-contactUrl">Contact Url</label>
                        <input type="text" class="form-control" name="contactUrl" id="acme-contact-contactUrl"
                            :class="{'valid': !$v.acmeContact.contactUrl.$invalid, 'invalid': $v.acmeContact.contactUrl.$invalid }" v-model="$v.acmeContact.contactUrl.$model"  required/>
                        <div v-if="$v.acmeContact.contactUrl.$anyDirty && $v.acmeContact.contactUrl.$invalid">
                            <small class="form-text text-danger" v-if="!$v.acmeContact.contactUrl.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ca3SApp.acmeContact.account')" for="acme-contact-account">Account</label>
                        <select class="form-control" id="acme-contact-account" name="account" v-model="acmeContact.account">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="acmeContact.account && aCMEAccountOption.id === acmeContact.account.id ? acmeContact.account : aCMEAccountOption" v-for="aCMEAccountOption in aCMEAccounts" :key="aCMEAccountOption.id">{{aCMEAccountOption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.acmeContact.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./acme-contact-update.component.ts">
</script>

// src/main/webapp/app/entities/acme-contact/acme-contact-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IAcmeContact, AcmeContact } from 'app/shared/model/acme-contact.model';
import { AcmeContactService } from './acme-contact.service';
import { IACMEAccount } from 'app/shared/model/acme-account.model';
import { ACMEAccountService } from 'app/entities/acme-account/acme-account.service';

@Component({
  selector: 'jhi-acme-contact-update',
  templateUrl: './acme-contact-update.component.html'
})
export class AcmeContactUpdateComponent implements OnInit {
  isSaving: boolean;

  acmeaccounts: IACMEAccount[];

  editForm = this.fb.group({
    id: [],
    contactId: [null, [Validators.required]],
    contactUrl: [null, [Validators.required]],
    account: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected acmeContactService: AcmeContactService,
    protected aCMEAccountService: ACMEAccountService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ acmeContact }) => {
      this.updateForm(acmeContact);
    });
    this.aCMEAccountService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IACMEAccount[]>) => mayBeOk.ok),
        map((response: HttpResponse<IACMEAccount[]>) => response.body)
      )
      .subscribe((res: IACMEAccount[]) => (this.acmeaccounts = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(acmeContact: IAcmeContact) {
    this.editForm.patchValue({
      id: acmeContact.id,
      contactId: acmeContact.contactId,
      contactUrl: acmeContact.contactUrl,
      account: acmeContact.account
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const acmeContact = this.createFromForm();
    if (acmeContact.id !== undefined) {
      this.subscribeToSaveResponse(this.acmeContactService.update(acmeContact));
    } else {
      this.subscribeToSaveResponse(this.acmeContactService.create(acmeContact));
    }
  }

  private createFromForm(): IAcmeContact {
    return {
      ...new AcmeContact(),
      id: this.editForm.get(['id']).value,
      contactId: this.editForm.get(['contactId']).value,
      contactUrl: this.editForm.get(['contactUrl']).value,
      account: this.editForm.get(['account']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IAcmeContact>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackACMEAccountById(index: number, item: IACMEAccount) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-acme-contact-heading" jhiTranslate="ca3SJhApp.acmeContact.home.createOrEditLabel">Create or edit a Acme Contact</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeContact.contactId" for="field_contactId">Contact Id</label>
                    <input type="number" class="form-control" name="contactId" id="field_contactId"
                           formControlName="contactId"/>
                    <div *ngIf="editForm.get('contactId').invalid && (editForm.get('contactId').dirty || editForm.get('contactId').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('contactId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('contactId')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeContact.contactUrl" for="field_contactUrl">Contact Url</label>
                    <input type="text" class="form-control" name="contactUrl" id="field_contactUrl"
                           formControlName="contactUrl"/>
                    <div *ngIf="editForm.get('contactUrl').invalid && (editForm.get('contactUrl').dirty || editForm.get('contactUrl').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('contactUrl').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeContact.account" for="field_account">Account</label>
                    <select class="form-control" id="field_account" name="account" formControlName="account">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="aCMEAccountOption.id === editForm.get('account').value?.id ? editForm.get('account').value : aCMEAccountOption" *ngFor="let aCMEAccountOption of acmeaccounts; trackBy: trackACMEAccountById">{{aCMEAccountOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
