// src/main/webapp/app/entities/acme-contact/acme-contact.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IAcmeContact } from 'app/shared/model/acme-contact.model';
import { AccountService } from 'app/core/auth/account.service';
import { AcmeContactService } from './acme-contact.service';

@Component({
  selector: 'jhi-acme-contact',
  templateUrl: './acme-contact.component.html'
})
export class AcmeContactComponent implements OnInit, OnDestroy {
  acmeContacts: IAcmeContact[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected acmeContactService: AcmeContactService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.acmeContactService
      .query()
      .pipe(
        filter((res: HttpResponse<IAcmeContact[]>) => res.ok),
        map((res: HttpResponse<IAcmeContact[]>) => res.body)
      )
      .subscribe(
        (res: IAcmeContact[]) => {
          this.acmeContacts = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInAcmeContacts();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IAcmeContact) {
    return item.id;
  }

  registerChangeInAcmeContacts() {
    this.eventSubscriber = this.eventManager.subscribe('acmeContactListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ca3SJhApp.acmeContact.home.title">Acme Contacts</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-acme-contact" [routerLink]="['/acme-contact/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ca3SJhApp.acmeContact.home.createLabel">
            Create a new Acme Contact
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="acmeContacts?.length === 0">
        <span jhiTranslate="ca3SJhApp.acmeContact.home.notFound">No acmeContacts found</span>
    </div>
    <div class="table-responsive" *ngIf="acmeContacts?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ca3SJhApp.acmeContact.contactId">Contact Id</span></th>
            <th><span jhiTranslate="ca3SJhApp.acmeContact.contactUrl">Contact Url</span></th>
            <th><span jhiTranslate="ca3SJhApp.acmeContact.account">Account</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let acmeContact of acmeContacts ;trackBy: trackId">
                <td><a [routerLink]="['/acme-contact', acmeContact.id, 'view' ]">{{acmeContact.id}}</a></td>
                <td>{{acmeContact.contactId}}</td>
                <td>{{acmeContact.contactUrl}}</td>
                <td>
                    <div *ngIf="acmeContact.account">
                        <a [routerLink]="['/acme-account', acmeContact.account?.id, 'view' ]" >{{acmeContact.account?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/acme-contact', acmeContact.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/acme-contact', acmeContact.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/acme-contact', { outlets: { popup: acmeContact.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/acme-contact/acme-contact.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ca3SApp.acmeContact.home.title')" id="acme-contact-heading">Acme Contacts</span>
            <router-link :to="{name: 'AcmeContactCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-acme-contact">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ca3SApp.acmeContact.home.createLabel')">
                    Create a new Acme Contact
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && acmeContacts && acmeContacts.length === 0">
            <span v-text="$t('ca3SApp.acmeContact.home.notFound')">No acmeContacts found</span>
        </div>
        <div class="table-responsive" v-if="acmeContacts && acmeContacts.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th><span v-text="$t('ca3SApp.acmeContact.contactId')">Contact Id</span></th>
                    <th><span v-text="$t('ca3SApp.acmeContact.contactUrl')">Contact Url</span></th>
                    <th><span v-text="$t('ca3SApp.acmeContact.account')">Account</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="acmeContact in acmeContacts"
                    :key="acmeContact.id">
                    <td>
                        <router-link :to="{name: 'AcmeContactView', params: {acmeContactId: acmeContact.id}}">{{acmeContact.id}}</router-link>
                    </td>
                    <td>{{acmeContact.contactId}}</td>
                    <td>{{acmeContact.contactUrl}}</td>
                    <td>
                        <div v-if="acmeContact.account">
                            <router-link :to="{name: 'ACMEAccountView', params: {aCMEAccountId: acmeContact.account.id}}">{{acmeContact.account.id}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'AcmeContactView', params: {acmeContactId: acmeContact.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'AcmeContactEdit', params: {acmeContactId: acmeContact.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(acmeContact)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ca3SApp.acmeContact.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-acmeContact-heading" v-bind:title="$t('ca3SApp.acmeContact.delete.question')">Are you sure you want to delete this Acme Contact?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-acmeContact" v-text="$t('entity.action.delete')" v-on:click="removeAcmeContact()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./acme-contact.component.ts">
</script>
