// src/main/webapp/app/entities/nonce/nonce-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import * as moment from 'moment';
import { INonce, Nonce } from 'app/shared/model/nonce.model';
import { NonceService } from './nonce.service';

@Component({
  selector: 'jhi-nonce-update',
  templateUrl: './nonce-update.component.html'
})
export class NonceUpdateComponent implements OnInit {
  isSaving: boolean;
  expiresAtDp: any;

  editForm = this.fb.group({
    id: [],
    nonceValue: [],
    expiresAt: []
  });

  constructor(protected nonceService: NonceService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ nonce }) => {
      this.updateForm(nonce);
    });
  }

  updateForm(nonce: INonce) {
    this.editForm.patchValue({
      id: nonce.id,
      nonceValue: nonce.nonceValue,
      expiresAt: nonce.expiresAt
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const nonce = this.createFromForm();
    if (nonce.id !== undefined) {
      this.subscribeToSaveResponse(this.nonceService.update(nonce));
    } else {
      this.subscribeToSaveResponse(this.nonceService.create(nonce));
    }
  }

  private createFromForm(): INonce {
    return {
      ...new Nonce(),
      id: this.editForm.get(['id']).value,
      nonceValue: this.editForm.get(['nonceValue']).value,
      expiresAt: this.editForm.get(['expiresAt']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<INonce>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-nonce-heading" jhiTranslate="ca3SJhApp.nonce.home.createOrEditLabel">Create or edit a Nonce</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.nonce.nonceValue" for="field_nonceValue">Nonce Value</label>
                    <input type="text" class="form-control" name="nonceValue" id="field_nonceValue"
                           formControlName="nonceValue"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.nonce.expiresAt" for="field_expiresAt">Expires At</label>
                    <div class="input-group">
                        <input id="field_expiresAt" type="text" class="form-control" name="expiresAt" ngbDatepicker  #expiresAtDp="ngbDatepicker" formControlName="expiresAt"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="expiresAtDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/nonce/nonce-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.nonce.home.createOrEditLabel" v-text="$t('ca3SApp.nonce.home.createOrEditLabel')">Create or edit a Nonce</h2>
                <div>
                    <div class="form-group" v-if="nonce.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="nonce.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.nonce.nonceValue')" for="nonce-nonceValue">Nonce Value</label>
                        <input type="text" class="form-control" name="nonceValue" id="nonce-nonceValue"
                            :class="{'valid': !$v.nonce.nonceValue.$invalid, 'invalid': $v.nonce.nonceValue.$invalid }" v-model="$v.nonce.nonceValue.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.nonce.expiresAt')" for="nonce-expiresAt">Expires At</label>
                        <div class="input-group">
                            <input id="nonce-expiresAt" type="date" class="form-control" name="expiresAt"  :class="{'valid': !$v.nonce.expiresAt.$invalid, 'invalid': $v.nonce.expiresAt.$invalid }"
                            v-model="$v.nonce.expiresAt.$model"  />
                        </div>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.nonce.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./nonce-update.component.ts">
</script>
