// src/main/webapp/app/entities/nonce/nonce.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { INonce } from 'app/shared/model/nonce.model';
import { AccountService } from 'app/core/auth/account.service';
import { NonceService } from './nonce.service';

@Component({
  selector: 'jhi-nonce',
  templateUrl: './nonce.component.html'
})
export class NonceComponent implements OnInit, OnDestroy {
  nonces: INonce[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected nonceService: NonceService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.nonceService
      .query()
      .pipe(
        filter((res: HttpResponse<INonce[]>) => res.ok),
        map((res: HttpResponse<INonce[]>) => res.body)
      )
      .subscribe(
        (res: INonce[]) => {
          this.nonces = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInNonces();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: INonce) {
    return item.id;
  }

  registerChangeInNonces() {
    this.eventSubscriber = this.eventManager.subscribe('nonceListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ca3SJhApp.nonce.home.title">Nonces</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-nonce" [routerLink]="['/nonce/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ca3SJhApp.nonce.home.createLabel">
            Create a new Nonce
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="nonces?.length === 0">
        <span jhiTranslate="ca3SJhApp.nonce.home.notFound">No nonces found</span>
    </div>
    <div class="table-responsive" *ngIf="nonces?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ca3SJhApp.nonce.nonceValue">Nonce Value</span></th>
            <th><span jhiTranslate="ca3SJhApp.nonce.expiresAt">Expires At</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let nonce of nonces ;trackBy: trackId">
                <td><a [routerLink]="['/nonce', nonce.id, 'view' ]">{{nonce.id}}</a></td>
                <td>{{nonce.nonceValue}}</td>
                <td>{{nonce.expiresAt | date:'mediumDate'}}</td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/nonce', nonce.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/nonce', nonce.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/nonce', { outlets: { popup: nonce.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/nonce/nonce.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ca3SApp.nonce.home.title')" id="nonce-heading">Nonces</span>
            <router-link :to="{name: 'NonceCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-nonce">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ca3SApp.nonce.home.createLabel')">
                    Create a new Nonce
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && nonces && nonces.length === 0">
            <span v-text="$t('ca3SApp.nonce.home.notFound')">No nonces found</span>
        </div>
        <div class="table-responsive" v-if="nonces && nonces.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th><span v-text="$t('ca3SApp.nonce.nonceValue')">Nonce Value</span></th>
                    <th><span v-text="$t('ca3SApp.nonce.expiresAt')">Expires At</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="nonce in nonces"
                    :key="nonce.id">
                    <td>
                        <router-link :to="{name: 'NonceView', params: {nonceId: nonce.id}}">{{nonce.id}}</router-link>
                    </td>
                    <td>{{nonce.nonceValue}}</td>
                    <td>{{nonce.expiresAt}}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'NonceView', params: {nonceId: nonce.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'NonceEdit', params: {nonceId: nonce.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(nonce)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ca3SApp.nonce.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-nonce-heading" v-bind:title="$t('ca3SApp.nonce.delete.question')">Are you sure you want to delete this Nonce?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-nonce" v-text="$t('entity.action.delete')" v-on:click="removeNonce()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./nonce.component.ts">
</script>
