// src/main/webapp/app/entities/ca-connector-config/ca-connector-config-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { ICAConnectorConfig, CAConnectorConfig } from 'app/shared/model/ca-connector-config.model';
import { CAConnectorConfigService } from './ca-connector-config.service';

@Component({
  selector: 'jhi-ca-connector-config-update',
  templateUrl: './ca-connector-config-update.component.html'
})
export class CAConnectorConfigUpdateComponent implements OnInit {
  isSaving: boolean;

  editForm = this.fb.group({
    id: [],
    configId: [null, [Validators.required]],
    name: [],
    caConnectorType: [],
    caUrl: [],
    secret: [],
    pollingOffset: [],
    defaultCA: [],
    active: []
  });

  constructor(
    protected cAConnectorConfigService: CAConnectorConfigService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ cAConnectorConfig }) => {
      this.updateForm(cAConnectorConfig);
    });
  }

  updateForm(cAConnectorConfig: ICAConnectorConfig) {
    this.editForm.patchValue({
      id: cAConnectorConfig.id,
      configId: cAConnectorConfig.configId,
      name: cAConnectorConfig.name,
      caConnectorType: cAConnectorConfig.caConnectorType,
      caUrl: cAConnectorConfig.caUrl,
      secret: cAConnectorConfig.secret,
      pollingOffset: cAConnectorConfig.pollingOffset,
      defaultCA: cAConnectorConfig.defaultCA,
      active: cAConnectorConfig.active
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const cAConnectorConfig = this.createFromForm();
    if (cAConnectorConfig.id !== undefined) {
      this.subscribeToSaveResponse(this.cAConnectorConfigService.update(cAConnectorConfig));
    } else {
      this.subscribeToSaveResponse(this.cAConnectorConfigService.create(cAConnectorConfig));
    }
  }

  private createFromForm(): ICAConnectorConfig {
    return {
      ...new CAConnectorConfig(),
      id: this.editForm.get(['id']).value,
      configId: this.editForm.get(['configId']).value,
      name: this.editForm.get(['name']).value,
      caConnectorType: this.editForm.get(['caConnectorType']).value,
      caUrl: this.editForm.get(['caUrl']).value,
      secret: this.editForm.get(['secret']).value,
      pollingOffset: this.editForm.get(['pollingOffset']).value,
      defaultCA: this.editForm.get(['defaultCA']).value,
      active: this.editForm.get(['active']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICAConnectorConfig>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-ca-connector-config-heading" jhiTranslate="ca3SJhApp.cAConnectorConfig.home.createOrEditLabel">Create or edit a CA Connector Config</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cAConnectorConfig.configId" for="field_configId">Config Id</label>
                    <input type="number" class="form-control" name="configId" id="field_configId"
                           formControlName="configId"/>
                    <div *ngIf="editForm.get('configId').invalid && (editForm.get('configId').dirty || editForm.get('configId').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('configId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('configId')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cAConnectorConfig.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                           formControlName="name"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cAConnectorConfig.caConnectorType" for="field_caConnectorType">Ca Connector Type</label>
                    <select class="form-control" name="caConnectorType" formControlName="caConnectorType" id="field_caConnectorType">
                        <option value="Internal">{{'ca3SJhApp.CAConnectorType.Internal' | translate}}</option>
                        <option value="Cmp">{{'ca3SJhApp.CAConnectorType.Cmp' | translate}}</option>
                        <option value="Adcs">{{'ca3SJhApp.CAConnectorType.Adcs' | translate}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cAConnectorConfig.caUrl" for="field_caUrl">Ca Url</label>
                    <input type="text" class="form-control" name="caUrl" id="field_caUrl"
                           formControlName="caUrl"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cAConnectorConfig.secret" for="field_secret">Secret</label>
                    <input type="text" class="form-control" name="secret" id="field_secret"
                           formControlName="secret"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cAConnectorConfig.pollingOffset" for="field_pollingOffset">Polling Offset</label>
                    <input type="number" class="form-control" name="pollingOffset" id="field_pollingOffset"
                           formControlName="pollingOffset"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cAConnectorConfig.defaultCA" for="field_defaultCA">Default CA</label>
                    <input type="checkbox" class="form-control" name="defaultCA" id="field_defaultCA"
                           formControlName="defaultCA"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.cAConnectorConfig.active" for="field_active">Active</label>
                    <input type="checkbox" class="form-control" name="active" id="field_active"
                           formControlName="active"/>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/core/ca-connector-config/ca-connector-config-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.cAConnectorConfig.home.createOrEditLabel" v-text="$t('ca3SApp.cAConnectorConfig.home.createOrEditLabel')">Create or edit a CAConnectorConfig</h2>
                <div>
                    <!--div class="form-group" v-if="cAConnectorConfig.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="cAConnectorConfig.id" readonly />
                    </div-->

                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cAConnectorConfig.name')" for="ca-connector-config-name">Name</label>
                        <input type="text" class="form-control" name="name" id="ca-connector-config-name"
                            :class="{'valid': !$v.cAConnectorConfig.name.$invalid, 'invalid': $v.cAConnectorConfig.name.$invalid }" v-model="$v.cAConnectorConfig.name.$model"  required/>
                        <div v-if="$v.cAConnectorConfig.name.$anyDirty && $v.cAConnectorConfig.name.$invalid">
                            <small class="form-text text-danger" v-if="!$v.cAConnectorConfig.name.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cAConnectorConfig.caConnectorType')" for="ca-connector-config-caConnectorType">Ca Connector Type</label>
                        <select class="form-control" name="caConnectorType"
                                :class="{'valid': !$v.cAConnectorConfig.caConnectorType.$invalid, 'invalid': $v.cAConnectorConfig.caConnectorType.$invalid }"
                                v-model="$v.cAConnectorConfig.caConnectorType.$model"
                                id="ca-connector-config-caConnectorType"  required>
                            <option value="INTERNAL" v-bind:label="$t('ca3SApp.CAConnectorType.INTERNAL')">INTERNAL</option>
                            <option value="CMP" v-bind:label="$t('ca3SApp.CAConnectorType.CMP')">CMP</option>
                            <option value="ADCS" v-bind:label="$t('ca3SApp.CAConnectorType.ADCS')">ADCS</option>
                            <option value="ADCS_CERTIFICATE_INVENTORY" v-bind:label="$t('ca3SApp.CAConnectorType.ADCS_CERTIFICATE_INVENTORY')">ADCS_CERTIFICATE_INVENTORY</option>
                            <option value="DIRECTORY" v-bind:label="$t('ca3SApp.CAConnectorType.DIRECTORY')">DIRECTORY</option>
                        </select>
                        <div v-if="$v.cAConnectorConfig.caConnectorType.$anyDirty && $v.cAConnectorConfig.caConnectorType.$invalid">
                            <small class="form-text text-danger" v-if="!$v.cAConnectorConfig.caConnectorType.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group" v-if="$v.cAConnectorConfig.caConnectorType.$model !== 'INTERNAL'">
                        <label class="form-control-label" v-text="$t('ca3SApp.cAConnectorConfig.caUrl')" for="ca-connector-config-caUrl">Ca Url</label>
                        <input type="text" class="form-control" name="caUrl" id="ca-connector-config-caUrl"
                            :class="{'valid': !$v.cAConnectorConfig.caUrl.$invalid, 'invalid': $v.cAConnectorConfig.caUrl.$invalid }" v-model="$v.cAConnectorConfig.caUrl.$model" />
                    </div>
                    <div class="form-group" v-if="$v.cAConnectorConfig.caConnectorType.$model === 'ADCS_CERTIFICATE_INVENTORY'">
                        <label class="form-control-label" v-text="$t('ca3SApp.cAConnectorConfig.pollingOffset')" for="ca-connector-config-pollingOffset">Polling Offset</label>
                        <input type="number" class="form-control" name="pollingOffset" id="ca-connector-config-pollingOffset"
                            :class="{'valid': !$v.cAConnectorConfig.pollingOffset.$invalid, 'invalid': $v.cAConnectorConfig.pollingOffset.$invalid }" v-model.number="$v.cAConnectorConfig.pollingOffset.$model" />
                    </div>
                    <div class="form-group" v-if="!($v.cAConnectorConfig.caConnectorType.$model === 'DIRECTORY' || $v.cAConnectorConfig.caConnectorType.$model === 'ADCS_CERTIFICATE_INVENTORY')">
                        <label class="form-control-label" v-text="$t('ca3SApp.cAConnectorConfig.defaultCA')" for="ca-connector-config-defaultCA">Default CA</label>
                        <input type="checkbox" class="form-check" name="defaultCA" id="ca-connector-config-defaultCA"
                               :class="{'valid': !$v.cAConnectorConfig.defaultCA.$invalid, 'invalid': $v.cAConnectorConfig.defaultCA.$invalid }" v-model="$v.cAConnectorConfig.defaultCA.$model" />
                    </div>
                    <div class="form-group" v-if="$v.cAConnectorConfig.caConnectorType.$model === 'DIRECTORY'">
                        <label class="form-control-label" v-text="$t('ca3SApp.cAConnectorConfig.trustSelfsignedCertificates')" for="ca-connector-config-trustSelfsignedCertificates">Trust Selfsigned Certificates</label>
                        <input type="checkbox" class="form-check" name="trustSelfsignedCertificates" id="ca-connector-config-trustSelfsignedCertificates"
                               :class="{'valid': !$v.cAConnectorConfig.trustSelfsignedCertificates.$invalid, 'invalid': $v.cAConnectorConfig.trustSelfsignedCertificates.$invalid }" v-model="$v.cAConnectorConfig.trustSelfsignedCertificates.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cAConnectorConfig.active')" for="ca-connector-config-active">Active</label>
                        <input type="checkbox" class="form-check" name="active" id="ca-connector-config-active"
                            :class="{'valid': !$v.cAConnectorConfig.active.$invalid, 'invalid': $v.cAConnectorConfig.active.$invalid }" v-model="$v.cAConnectorConfig.active.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cAConnectorConfig.selector')" for="ca-connector-config-selector">Selector</label>
                        <input type="text" class="form-control" name="selector" id="ca-connector-config-selector"
                            :class="{'valid': !$v.cAConnectorConfig.selector.$invalid, 'invalid': $v.cAConnectorConfig.selector.$invalid }" v-model="$v.cAConnectorConfig.selector.$model" />
                    </div>
                    <div class="form-group" v-if="$v.cAConnectorConfig.caConnectorType.$model === 'DIRECTORY' || $v.cAConnectorConfig.caConnectorType.$model === 'ADCS_CERTIFICATE_INVENTORY' ">
                        <label class="form-control-label" v-text="$t('ca3SApp.cAConnectorConfig.interval')" for="ca-connector-config-interval">Interval</label>
                        <select class="form-control" name="interval" :class="{'valid': !$v.cAConnectorConfig.interval.$invalid, 'invalid': $v.cAConnectorConfig.interval.$invalid }" v-model="$v.cAConnectorConfig.interval.$model" id="ca-connector-config-interval" >
                            <option value="MINUTE" v-bind:label="$t('ca3SApp.Interval.MINUTE')">MINUTE</option>
                            <option value="HOUR" v-bind:label="$t('ca3SApp.Interval.HOUR')">HOUR</option>
                            <option value="DAY" v-bind:label="$t('ca3SApp.Interval.DAY')">DAY</option>
                            <option value="WEEK" v-bind:label="$t('ca3SApp.Interval.WEEK')">WEEK</option>
                            <option value="MONTH" v-bind:label="$t('ca3SApp.Interval.MONTH')">MONTH</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.cAConnectorConfig.plainSecret')" for="ca-connector-config-plainSecret">Passphrase</label>
                        <input type="password" class="form-control" name="plainSecret" id="ca-connector-config-plainSecret"
                            :class="{'valid': !$v.cAConnectorConfig.plainSecret.$invalid, 'invalid': $v.cAConnectorConfig.plainSecret.$invalid }" v-model="$v.cAConnectorConfig.plainSecret.$model" />
                    </div>

                    <div>
                        <audit-tag :caConnectorId="cAConnectorConfig.id" showLinks="false" :title="$t('ca3SApp.certificate.audit')"></audit-tag>
                    </div>

                </div>
                <div>
                    <!--button type="button" id="test" class="btn btn-secondary" v-on:click="testCaConnectorConfig()">
                        <font-awesome-icon icon="stethoscope"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.test')">Test</span>
                    </button-->
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.cAConnectorConfig.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./ca-connector-config-update.component.ts">
</script>
