// src/main/webapp/app/entities/acme-challenge/acme-challenge-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.acmeChallenge.home.createOrEditLabel" v-text="$t('ca3SApp.acmeChallenge.home.createOrEditLabel')">Create or edit a AcmeChallenge</h2>
                <div>
                    <div class="form-group" v-if="acmeChallenge.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="acmeChallenge.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeChallenge.challengeId')" for="acme-challenge-challengeId">Challenge Id</label>
                        <input type="number" class="form-control" name="challengeId" id="acme-challenge-challengeId"
                            :class="{'valid': !$v.acmeChallenge.challengeId.$invalid, 'invalid': $v.acmeChallenge.challengeId.$invalid }" v-model.number="$v.acmeChallenge.challengeId.$model"  required/>
                        <div v-if="$v.acmeChallenge.challengeId.$anyDirty && $v.acmeChallenge.challengeId.$invalid">
                            <small class="form-text text-danger" v-if="!$v.acmeChallenge.challengeId.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.acmeChallenge.challengeId.number" v-text="$t('entity.validation.number')">
                                This field should be a number.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeChallenge.type')" for="acme-challenge-type">Type</label>
                        <input type="text" class="form-control" name="type" id="acme-challenge-type"
                            :class="{'valid': !$v.acmeChallenge.type.$invalid, 'invalid': $v.acmeChallenge.type.$invalid }" v-model="$v.acmeChallenge.type.$model"  required/>
                        <div v-if="$v.acmeChallenge.type.$anyDirty && $v.acmeChallenge.type.$invalid">
                            <small class="form-text text-danger" v-if="!$v.acmeChallenge.type.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeChallenge.value')" for="acme-challenge-value">Value</label>
                        <input type="text" class="form-control" name="value" id="acme-challenge-value"
                            :class="{'valid': !$v.acmeChallenge.value.$invalid, 'invalid': $v.acmeChallenge.value.$invalid }" v-model="$v.acmeChallenge.value.$model"  required/>
                        <div v-if="$v.acmeChallenge.value.$anyDirty && $v.acmeChallenge.value.$invalid">
                            <small class="form-text text-danger" v-if="!$v.acmeChallenge.value.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeChallenge.token')" for="acme-challenge-token">Token</label>
                        <input type="text" class="form-control" name="token" id="acme-challenge-token"
                            :class="{'valid': !$v.acmeChallenge.token.$invalid, 'invalid': $v.acmeChallenge.token.$invalid }" v-model="$v.acmeChallenge.token.$model"  required/>
                        <div v-if="$v.acmeChallenge.token.$anyDirty && $v.acmeChallenge.token.$invalid">
                            <small class="form-text text-danger" v-if="!$v.acmeChallenge.token.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeChallenge.validated')" for="acme-challenge-validated">Validated</label>
                        <div class="input-group">
                            <input id="acme-challenge-validated" type="date" class="form-control" name="validated"  :class="{'valid': !$v.acmeChallenge.validated.$invalid, 'invalid': $v.acmeChallenge.validated.$invalid }"
                            v-model="$v.acmeChallenge.validated.$model"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeChallenge.status')" for="acme-challenge-status">Status</label>
                        <select class="form-control" name="status" :class="{'valid': !$v.acmeChallenge.status.$invalid, 'invalid': $v.acmeChallenge.status.$invalid }" v-model="$v.acmeChallenge.status.$model" id="acme-challenge-status"  required>
                            <option value="PENDING" v-bind:label="$t('ca3SApp.ChallengeStatus.PENDING')">PENDING</option>
                            <option value="VALID" v-bind:label="$t('ca3SApp.ChallengeStatus.VALID')">VALID</option>
                            <option value="INVALID" v-bind:label="$t('ca3SApp.ChallengeStatus.INVALID')">INVALID</option>
                            <option value="DEACTIVATED" v-bind:label="$t('ca3SApp.ChallengeStatus.DEACTIVATED')">DEACTIVATED</option>
                            <option value="EXPIRED" v-bind:label="$t('ca3SApp.ChallengeStatus.EXPIRED')">EXPIRED</option>
                            <option value="REVOKED" v-bind:label="$t('ca3SApp.ChallengeStatus.REVOKED')">REVOKED</option>
                        </select>
                        <div v-if="$v.acmeChallenge.status.$anyDirty && $v.acmeChallenge.status.$invalid">
                            <small class="form-text text-danger" v-if="!$v.acmeChallenge.status.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ca3SApp.acmeChallenge.authorization')" for="acme-challenge-authorization">Authorization</label>
                        <select class="form-control" id="acme-challenge-authorization" name="authorization" v-model="acmeChallenge.authorization">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="acmeChallenge.authorization && authorizationOption.id === acmeChallenge.authorization.id ? acmeChallenge.authorization : authorizationOption" v-for="authorizationOption in authorizations" :key="authorizationOption.id">{{authorizationOption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.acmeChallenge.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./acme-challenge-update.component.ts">
</script>

// src/main/webapp/app/entities/acme-challenge/acme-challenge-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import * as moment from 'moment';
import { JhiAlertService } from 'ng-jhipster';
import { IAcmeChallenge, AcmeChallenge } from 'app/shared/model/acme-challenge.model';
import { AcmeChallengeService } from './acme-challenge.service';
import { IAuthorization } from 'app/shared/model/authorization.model';
import { AuthorizationService } from 'app/entities/authorization/authorization.service';

@Component({
  selector: 'jhi-acme-challenge-update',
  templateUrl: './acme-challenge-update.component.html'
})
export class AcmeChallengeUpdateComponent implements OnInit {
  isSaving: boolean;

  authorizations: IAuthorization[];
  validatedDp: any;

  editForm = this.fb.group({
    id: [],
    challengeId: [null, [Validators.required]],
    type: [null, [Validators.required]],
    value: [null, [Validators.required]],
    token: [null, [Validators.required]],
    validated: [],
    status: [null, [Validators.required]],
    authorization: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected acmeChallengeService: AcmeChallengeService,
    protected authorizationService: AuthorizationService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ acmeChallenge }) => {
      this.updateForm(acmeChallenge);
    });
    this.authorizationService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IAuthorization[]>) => mayBeOk.ok),
        map((response: HttpResponse<IAuthorization[]>) => response.body)
      )
      .subscribe((res: IAuthorization[]) => (this.authorizations = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(acmeChallenge: IAcmeChallenge) {
    this.editForm.patchValue({
      id: acmeChallenge.id,
      challengeId: acmeChallenge.challengeId,
      type: acmeChallenge.type,
      value: acmeChallenge.value,
      token: acmeChallenge.token,
      validated: acmeChallenge.validated,
      status: acmeChallenge.status,
      authorization: acmeChallenge.authorization
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const acmeChallenge = this.createFromForm();
    if (acmeChallenge.id !== undefined) {
      this.subscribeToSaveResponse(this.acmeChallengeService.update(acmeChallenge));
    } else {
      this.subscribeToSaveResponse(this.acmeChallengeService.create(acmeChallenge));
    }
  }

  private createFromForm(): IAcmeChallenge {
    return {
      ...new AcmeChallenge(),
      id: this.editForm.get(['id']).value,
      challengeId: this.editForm.get(['challengeId']).value,
      type: this.editForm.get(['type']).value,
      value: this.editForm.get(['value']).value,
      token: this.editForm.get(['token']).value,
      validated: this.editForm.get(['validated']).value,
      status: this.editForm.get(['status']).value,
      authorization: this.editForm.get(['authorization']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IAcmeChallenge>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackAuthorizationById(index: number, item: IAuthorization) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-acme-challenge-heading" jhiTranslate="ca3SJhApp.acmeChallenge.home.createOrEditLabel">Create or edit a Acme Challenge</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeChallenge.challengeId" for="field_challengeId">Challenge Id</label>
                    <input type="number" class="form-control" name="challengeId" id="field_challengeId"
                           formControlName="challengeId"/>
                    <div *ngIf="editForm.get('challengeId').invalid && (editForm.get('challengeId').dirty || editForm.get('challengeId').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('challengeId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('challengeId')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeChallenge.type" for="field_type">Type</label>
                    <input type="text" class="form-control" name="type" id="field_type"
                           formControlName="type"/>
                    <div *ngIf="editForm.get('type').invalid && (editForm.get('type').dirty || editForm.get('type').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('type').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeChallenge.value" for="field_value">Value</label>
                    <input type="text" class="form-control" name="value" id="field_value"
                           formControlName="value"/>
                    <div *ngIf="editForm.get('value').invalid && (editForm.get('value').dirty || editForm.get('value').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('value').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeChallenge.token" for="field_token">Token</label>
                    <input type="text" class="form-control" name="token" id="field_token"
                           formControlName="token"/>
                    <div *ngIf="editForm.get('token').invalid && (editForm.get('token').dirty || editForm.get('token').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('token').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeChallenge.validated" for="field_validated">Validated</label>
                    <div class="input-group">
                        <input id="field_validated" type="text" class="form-control" name="validated" ngbDatepicker  #validatedDp="ngbDatepicker" formControlName="validated"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="validatedDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeChallenge.status" for="field_status">Status</label>
                    <select class="form-control" name="status" formControlName="status" id="field_status">
                        <option value="Pending">{{'ca3SJhApp.ChallengeStatus.Pending' | translate}}</option>
                        <option value="Valid">{{'ca3SJhApp.ChallengeStatus.Valid' | translate}}</option>
                        <option value="Invalid">{{'ca3SJhApp.ChallengeStatus.Invalid' | translate}}</option>
                        <option value="Deactivated">{{'ca3SJhApp.ChallengeStatus.Deactivated' | translate}}</option>
                        <option value="Expired">{{'ca3SJhApp.ChallengeStatus.Expired' | translate}}</option>
                        <option value="Revoked">{{'ca3SJhApp.ChallengeStatus.Revoked' | translate}}</option>
                    </select>
                    <div *ngIf="editForm.get('status').invalid && (editForm.get('status').dirty || editForm.get('status').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('status').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeChallenge.authorization" for="field_authorization">Authorization</label>
                    <select class="form-control" id="field_authorization" name="authorization" formControlName="authorization">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="authorizationOption.id === editForm.get('authorization').value?.id ? editForm.get('authorization').value : authorizationOption" *ngFor="let authorizationOption of authorizations; trackBy: trackAuthorizationById">{{authorizationOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
