// src/main/webapp/app/entities/acme-challenge/acme-challenge.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IAcmeChallenge } from 'app/shared/model/acme-challenge.model';
import { AccountService } from 'app/core/auth/account.service';
import { AcmeChallengeService } from './acme-challenge.service';

@Component({
  selector: 'jhi-acme-challenge',
  templateUrl: './acme-challenge.component.html'
})
export class AcmeChallengeComponent implements OnInit, OnDestroy {
  acmeChallenges: IAcmeChallenge[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected acmeChallengeService: AcmeChallengeService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.acmeChallengeService
      .query()
      .pipe(
        filter((res: HttpResponse<IAcmeChallenge[]>) => res.ok),
        map((res: HttpResponse<IAcmeChallenge[]>) => res.body)
      )
      .subscribe(
        (res: IAcmeChallenge[]) => {
          this.acmeChallenges = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInAcmeChallenges();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IAcmeChallenge) {
    return item.id;
  }

  registerChangeInAcmeChallenges() {
    this.eventSubscriber = this.eventManager.subscribe('acmeChallengeListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ca3SJhApp.acmeChallenge.home.title">Acme Challenges</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-acme-challenge" [routerLink]="['/acme-challenge/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ca3SJhApp.acmeChallenge.home.createLabel">
            Create a new Acme Challenge
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="acmeChallenges?.length === 0">
        <span jhiTranslate="ca3SJhApp.acmeChallenge.home.notFound">No acmeChallenges found</span>
    </div>
    <div class="table-responsive" *ngIf="acmeChallenges?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ca3SJhApp.acmeChallenge.type">Type</span></th>
            <th><span jhiTranslate="ca3SJhApp.acmeChallenge.value">Value</span></th>
            <th><span jhiTranslate="ca3SJhApp.acmeChallenge.token">Token</span></th>
            <th><span jhiTranslate="ca3SJhApp.acmeChallenge.validated">Validated</span></th>
            <th><span jhiTranslate="ca3SJhApp.acmeChallenge.status">Status</span></th>
            <th><span jhiTranslate="ca3SJhApp.acmeChallenge.authorization">Authorization</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let acmeChallenge of acmeChallenges ;trackBy: trackId">
                <td><a [routerLink]="['/acme-challenge', acmeChallenge.id, 'view' ]">{{acmeChallenge.id}}</a></td>
                <td>{{acmeChallenge.type}}</td>
                <td>{{acmeChallenge.value}}</td>
                <td>{{acmeChallenge.token}}</td>
                <td>{{acmeChallenge.validated | date:'mediumDate'}}</td>
                <td jhiTranslate="{{'ca3SJhApp.ChallengeStatus.' + acmeChallenge.status}}">{{acmeChallenge.status}}</td>
                <td>
                    <div *ngIf="acmeChallenge.authorization">
                        <a [routerLink]="['/authorization', acmeChallenge.authorization?.id, 'view' ]" >{{acmeChallenge.authorization?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/acme-challenge', acmeChallenge.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/acme-challenge', acmeChallenge.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/acme-challenge', { outlets: { popup: acmeChallenge.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/acme-challenge/acme-challenge.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ca3SApp.acmeChallenge.home.title')" id="acme-challenge-heading">Acme Challenges</span>
            <router-link :to="{name: 'AcmeChallengeCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-acme-challenge">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ca3SApp.acmeChallenge.home.createLabel')">
                    Create a new Acme Challenge
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && acmeChallenges && acmeChallenges.length === 0">
            <span v-text="$t('ca3SApp.acmeChallenge.home.notFound')">No acmeChallenges found</span>
        </div>
        <div class="table-responsive" v-if="acmeChallenges && acmeChallenges.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th><span v-text="$t('global.field.id')">ID</span></th>
                    <th><span v-text="$t('ca3SApp.acmeChallenge.challengeId')">Challenge Id</span></th>
                    <th><span v-text="$t('ca3SApp.acmeChallenge.type')">Type</span></th>
                    <th><span v-text="$t('ca3SApp.acmeChallenge.value')">Value</span></th>
                    <th><span v-text="$t('ca3SApp.acmeChallenge.token')">Token</span></th>
                    <th><span v-text="$t('ca3SApp.acmeChallenge.validated')">Validated</span></th>
                    <th><span v-text="$t('ca3SApp.acmeChallenge.status')">Status</span></th>
                    <th><span v-text="$t('ca3SApp.acmeChallenge.acmeAuthorization')">Acme Authorization</span></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="acmeChallenge in acmeChallenges"
                    :key="acmeChallenge.id">
                    <td>
                        <router-link :to="{name: 'AcmeChallengeView', params: {acmeChallengeId: acmeChallenge.id}}">{{acmeChallenge.id}}</router-link>
                    </td>
                    <td>{{acmeChallenge.challengeId}}</td>
                    <td>{{acmeChallenge.type}}</td>
                    <td>{{acmeChallenge.value}}</td>
                    <td>{{acmeChallenge.token}}</td>
                    <td>{{acmeChallenge.validated ? $d(Date.parse(acmeChallenge.validated), 'short') : ''}}</td>
                    <td v-text="$t('ca3SApp.ChallengeStatus.' + acmeChallenge.status)">{{acmeChallenge.status}}</td>
                    <td>
                        <div v-if="acmeChallenge.acmeAuthorization">
                            <router-link :to="{name: 'AcmeAuthorizationView', params: {acmeAuthorizationId: acmeChallenge.acmeAuthorization.id}}">{{acmeChallenge.acmeAuthorization.id}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'AcmeChallengeView', params: {acmeChallengeId: acmeChallenge.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'AcmeChallengeEdit', params: {acmeChallengeId: acmeChallenge.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(acmeChallenge)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ca3SApp.acmeChallenge.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-acmeChallenge-heading" v-text="$t('ca3SApp.acmeChallenge.delete.question', {'id': removeId})">Are you sure you want to delete this Acme Challenge?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-acmeChallenge" v-text="$t('entity.action.delete')" v-on:click="removeAcmeChallenge()">Delete</button>
            </div>
        </b-modal>
    </div>
</template>

<script lang="ts" src="./acme-challenge.component.ts">
</script>
