// src/main/webapp/app/entities/authorization/authorization-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.authorization.home.createOrEditLabel" v-text="$t('ca3SApp.authorization.home.createOrEditLabel')">Create or edit a Authorization</h2>
                <div>
                    <div class="form-group" v-if="authorization.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="authorization.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.authorization.authorizationId')" for="authorization-authorizationId">Authorization Id</label>
                        <input type="number" class="form-control" name="authorizationId" id="authorization-authorizationId"
                            :class="{'valid': !$v.authorization.authorizationId.$invalid, 'invalid': $v.authorization.authorizationId.$invalid }" v-model.number="$v.authorization.authorizationId.$model"  required/>
                        <div v-if="$v.authorization.authorizationId.$anyDirty && $v.authorization.authorizationId.$invalid">
                            <small class="form-text text-danger" v-if="!$v.authorization.authorizationId.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.authorization.authorizationId.number" v-text="$t('entity.validation.number')">
                                This field should be a number.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.authorization.type')" for="authorization-type">Type</label>
                        <input type="text" class="form-control" name="type" id="authorization-type"
                            :class="{'valid': !$v.authorization.type.$invalid, 'invalid': $v.authorization.type.$invalid }" v-model="$v.authorization.type.$model"  required/>
                        <div v-if="$v.authorization.type.$anyDirty && $v.authorization.type.$invalid">
                            <small class="form-text text-danger" v-if="!$v.authorization.type.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.authorization.value')" for="authorization-value">Value</label>
                        <input type="text" class="form-control" name="value" id="authorization-value"
                            :class="{'valid': !$v.authorization.value.$invalid, 'invalid': $v.authorization.value.$invalid }" v-model="$v.authorization.value.$model"  required/>
                        <div v-if="$v.authorization.value.$anyDirty && $v.authorization.value.$invalid">
                            <small class="form-text text-danger" v-if="!$v.authorization.value.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ca3SApp.authorization.order')" for="authorization-order">Order</label>
                        <select class="form-control" id="authorization-order" name="order" v-model="authorization.order">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="authorization.order && acmeOrderOption.id === authorization.order.id ? authorization.order : acmeOrderOption" v-for="acmeOrderOption in acmeOrders" :key="acmeOrderOption.id">{{acmeOrderOption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.authorization.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./authorization-update.component.ts">
</script>

// src/main/webapp/app/entities/authorization/authorization-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IAuthorization, Authorization } from 'app/shared/model/authorization.model';
import { AuthorizationService } from './authorization.service';
import { IAcmeOrder } from 'app/shared/model/acme-order.model';
import { AcmeOrderService } from 'app/entities/acme-order/acme-order.service';

@Component({
  selector: 'jhi-authorization-update',
  templateUrl: './authorization-update.component.html'
})
export class AuthorizationUpdateComponent implements OnInit {
  isSaving: boolean;

  acmeorders: IAcmeOrder[];

  editForm = this.fb.group({
    id: [],
    authorizationId: [null, [Validators.required]],
    type: [null, [Validators.required]],
    value: [null, [Validators.required]],
    order: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected authorizationService: AuthorizationService,
    protected acmeOrderService: AcmeOrderService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ authorization }) => {
      this.updateForm(authorization);
    });
    this.acmeOrderService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IAcmeOrder[]>) => mayBeOk.ok),
        map((response: HttpResponse<IAcmeOrder[]>) => response.body)
      )
      .subscribe((res: IAcmeOrder[]) => (this.acmeorders = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(authorization: IAuthorization) {
    this.editForm.patchValue({
      id: authorization.id,
      authorizationId: authorization.authorizationId,
      type: authorization.type,
      value: authorization.value,
      order: authorization.order
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const authorization = this.createFromForm();
    if (authorization.id !== undefined) {
      this.subscribeToSaveResponse(this.authorizationService.update(authorization));
    } else {
      this.subscribeToSaveResponse(this.authorizationService.create(authorization));
    }
  }

  private createFromForm(): IAuthorization {
    return {
      ...new Authorization(),
      id: this.editForm.get(['id']).value,
      authorizationId: this.editForm.get(['authorizationId']).value,
      type: this.editForm.get(['type']).value,
      value: this.editForm.get(['value']).value,
      order: this.editForm.get(['order']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IAuthorization>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackAcmeOrderById(index: number, item: IAcmeOrder) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-authorization-heading" jhiTranslate="ca3SJhApp.authorization.home.createOrEditLabel">Create or edit a Authorization</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.authorization.authorizationId" for="field_authorizationId">Authorization Id</label>
                    <input type="number" class="form-control" name="authorizationId" id="field_authorizationId"
                           formControlName="authorizationId"/>
                    <div *ngIf="editForm.get('authorizationId').invalid && (editForm.get('authorizationId').dirty || editForm.get('authorizationId').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('authorizationId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('authorizationId')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.authorization.type" for="field_type">Type</label>
                    <input type="text" class="form-control" name="type" id="field_type"
                           formControlName="type"/>
                    <div *ngIf="editForm.get('type').invalid && (editForm.get('type').dirty || editForm.get('type').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('type').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.authorization.value" for="field_value">Value</label>
                    <input type="text" class="form-control" name="value" id="field_value"
                           formControlName="value"/>
                    <div *ngIf="editForm.get('value').invalid && (editForm.get('value').dirty || editForm.get('value').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('value').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.authorization.order" for="field_order">Order</label>
                    <select class="form-control" id="field_order" name="order" formControlName="order">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="acmeOrderOption.id === editForm.get('order').value?.id ? editForm.get('order').value : acmeOrderOption" *ngFor="let acmeOrderOption of acmeorders; trackBy: trackAcmeOrderById">{{acmeOrderOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
