// src/main/webapp/app/entities/acme-order/acme-order-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ca3SApp.acmeOrder.home.createOrEditLabel" v-text="$t('ca3SApp.acmeOrder.home.createOrEditLabel')">Create or edit a AcmeOrder</h2>
                <div>
                    <div class="form-group" v-if="acmeOrder.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="acmeOrder.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeOrder.orderId')" for="acme-order-orderId">Order Id</label>
                        <input type="number" class="form-control" name="orderId" id="acme-order-orderId"
                            :class="{'valid': !$v.acmeOrder.orderId.$invalid, 'invalid': $v.acmeOrder.orderId.$invalid }" v-model.number="$v.acmeOrder.orderId.$model"  required/>
                        <div v-if="$v.acmeOrder.orderId.$anyDirty && $v.acmeOrder.orderId.$invalid">
                            <small class="form-text text-danger" v-if="!$v.acmeOrder.orderId.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.acmeOrder.orderId.number" v-text="$t('entity.validation.number')">
                                This field should be a number.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeOrder.status')" for="acme-order-status">Status</label>
                        <select class="form-control" name="status" :class="{'valid': !$v.acmeOrder.status.$invalid, 'invalid': $v.acmeOrder.status.$invalid }" v-model="$v.acmeOrder.status.$model" id="acme-order-status"  required>
                            <option value="PENDING" v-bind:label="$t('ca3SApp.OrderStatus.PENDING')">PENDING</option>
                            <option value="READY" v-bind:label="$t('ca3SApp.OrderStatus.READY')">READY</option>
                            <option value="PROCESSING" v-bind:label="$t('ca3SApp.OrderStatus.PROCESSING')">PROCESSING</option>
                            <option value="VALID" v-bind:label="$t('ca3SApp.OrderStatus.VALID')">VALID</option>
                            <option value="INVALID" v-bind:label="$t('ca3SApp.OrderStatus.INVALID')">INVALID</option>
                        </select>
                        <div v-if="$v.acmeOrder.status.$anyDirty && $v.acmeOrder.status.$invalid">
                            <small class="form-text text-danger" v-if="!$v.acmeOrder.status.required" v-text="$t('entity.validation.required')">
                                This field is required.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeOrder.expires')" for="acme-order-expires">Expires</label>
                        <div class="input-group">
                            <input id="acme-order-expires" type="date" class="form-control" name="expires"  :class="{'valid': !$v.acmeOrder.expires.$invalid, 'invalid': $v.acmeOrder.expires.$invalid }"
                            v-model="$v.acmeOrder.expires.$model"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeOrder.notBefore')" for="acme-order-notBefore">Not Before</label>
                        <div class="input-group">
                            <input id="acme-order-notBefore" type="date" class="form-control" name="notBefore"  :class="{'valid': !$v.acmeOrder.notBefore.$invalid, 'invalid': $v.acmeOrder.notBefore.$invalid }"
                            v-model="$v.acmeOrder.notBefore.$model"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeOrder.notAfter')" for="acme-order-notAfter">Not After</label>
                        <div class="input-group">
                            <input id="acme-order-notAfter" type="date" class="form-control" name="notAfter"  :class="{'valid': !$v.acmeOrder.notAfter.$invalid, 'invalid': $v.acmeOrder.notAfter.$invalid }"
                            v-model="$v.acmeOrder.notAfter.$model"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeOrder.error')" for="acme-order-error">Error</label>
                        <input type="text" class="form-control" name="error" id="acme-order-error"
                            :class="{'valid': !$v.acmeOrder.error.$invalid, 'invalid': $v.acmeOrder.error.$invalid }" v-model="$v.acmeOrder.error.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeOrder.finalizeUrl')" for="acme-order-finalizeUrl">Finalize Url</label>
                        <input type="text" class="form-control" name="finalizeUrl" id="acme-order-finalizeUrl"
                            :class="{'valid': !$v.acmeOrder.finalizeUrl.$invalid, 'invalid': $v.acmeOrder.finalizeUrl.$invalid }" v-model="$v.acmeOrder.finalizeUrl.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ca3SApp.acmeOrder.certificateUrl')" for="acme-order-certificateUrl">Certificate Url</label>
                        <input type="text" class="form-control" name="certificateUrl" id="acme-order-certificateUrl"
                            :class="{'valid': !$v.acmeOrder.certificateUrl.$invalid, 'invalid': $v.acmeOrder.certificateUrl.$invalid }" v-model="$v.acmeOrder.certificateUrl.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ca3SApp.acmeOrder.csr')" for="acme-order-csr">Csr</label>
                        <select class="form-control" id="acme-order-csr" name="csr" v-model="acmeOrder.csr">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="acmeOrder.csr && cSROption.id === acmeOrder.csr.id ? acmeOrder.csr : cSROption" v-for="cSROption in cSRS" :key="cSROption.id">{{cSROption.id}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ca3SApp.acmeOrder.certificate')" for="acme-order-certificate">Certificate</label>
                        <select class="form-control" id="acme-order-certificate" name="certificate" v-model="acmeOrder.certificate">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="acmeOrder.certificate && certificateOption.id === acmeOrder.certificate.id ? acmeOrder.certificate : certificateOption" v-for="certificateOption in certificates" :key="certificateOption.id">{{certificateOption.id}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ca3SApp.acmeOrder.account')" for="acme-order-account">Account</label>
                        <select class="form-control" id="acme-order-account" name="account" v-model="acmeOrder.account">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="acmeOrder.account && aCMEAccountOption.id === acmeOrder.account.id ? acmeOrder.account : aCMEAccountOption" v-for="aCMEAccountOption in aCMEAccounts" :key="aCMEAccountOption.id">{{aCMEAccountOption.id}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.acmeOrder.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./acme-order-update.component.ts">
</script>

// src/main/webapp/app/entities/acme-order/acme-order-update.component.ts
import { Component, OnInit } from '@angular/core';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import * as moment from 'moment';
import { JhiAlertService } from 'ng-jhipster';
import { IAcmeOrder, AcmeOrder } from 'app/shared/model/acme-order.model';
import { AcmeOrderService } from './acme-order.service';
import { ICSR } from 'app/shared/model/csr.model';
import { CSRService } from 'app/entities/csr/csr.service';
import { ICertificate } from 'app/shared/model/certificate.model';
import { CertificateService } from 'app/entities/certificate/certificate.service';
import { IACMEAccount } from 'app/shared/model/acme-account.model';
import { ACMEAccountService } from 'app/entities/acme-account/acme-account.service';

@Component({
  selector: 'jhi-acme-order-update',
  templateUrl: './acme-order-update.component.html'
})
export class AcmeOrderUpdateComponent implements OnInit {
  isSaving: boolean;

  csrs: ICSR[];

  certificates: ICertificate[];

  acmeaccounts: IACMEAccount[];
  expiresDp: any;
  notBeforeDp: any;
  notAfterDp: any;

  editForm = this.fb.group({
    id: [],
    orderId: [null, [Validators.required]],
    status: [null, [Validators.required]],
    expires: [],
    notBefore: [],
    notAfter: [],
    error: [],
    finalizeUrl: [],
    certificateUrl: [],
    csr: [],
    certificate: [],
    account: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected acmeOrderService: AcmeOrderService,
    protected cSRService: CSRService,
    protected certificateService: CertificateService,
    protected aCMEAccountService: ACMEAccountService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ acmeOrder }) => {
      this.updateForm(acmeOrder);
    });
    this.cSRService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICSR[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICSR[]>) => response.body)
      )
      .subscribe((res: ICSR[]) => (this.csrs = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.certificateService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICertificate[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICertificate[]>) => response.body)
      )
      .subscribe((res: ICertificate[]) => (this.certificates = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.aCMEAccountService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IACMEAccount[]>) => mayBeOk.ok),
        map((response: HttpResponse<IACMEAccount[]>) => response.body)
      )
      .subscribe((res: IACMEAccount[]) => (this.acmeaccounts = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(acmeOrder: IAcmeOrder) {
    this.editForm.patchValue({
      id: acmeOrder.id,
      orderId: acmeOrder.orderId,
      status: acmeOrder.status,
      expires: acmeOrder.expires,
      notBefore: acmeOrder.notBefore,
      notAfter: acmeOrder.notAfter,
      error: acmeOrder.error,
      finalizeUrl: acmeOrder.finalizeUrl,
      certificateUrl: acmeOrder.certificateUrl,
      csr: acmeOrder.csr,
      certificate: acmeOrder.certificate,
      account: acmeOrder.account
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const acmeOrder = this.createFromForm();
    if (acmeOrder.id !== undefined) {
      this.subscribeToSaveResponse(this.acmeOrderService.update(acmeOrder));
    } else {
      this.subscribeToSaveResponse(this.acmeOrderService.create(acmeOrder));
    }
  }

  private createFromForm(): IAcmeOrder {
    return {
      ...new AcmeOrder(),
      id: this.editForm.get(['id']).value,
      orderId: this.editForm.get(['orderId']).value,
      status: this.editForm.get(['status']).value,
      expires: this.editForm.get(['expires']).value,
      notBefore: this.editForm.get(['notBefore']).value,
      notAfter: this.editForm.get(['notAfter']).value,
      error: this.editForm.get(['error']).value,
      finalizeUrl: this.editForm.get(['finalizeUrl']).value,
      certificateUrl: this.editForm.get(['certificateUrl']).value,
      csr: this.editForm.get(['csr']).value,
      certificate: this.editForm.get(['certificate']).value,
      account: this.editForm.get(['account']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IAcmeOrder>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackCSRById(index: number, item: ICSR) {
    return item.id;
  }

  trackCertificateById(index: number, item: ICertificate) {
    return item.id;
  }

  trackACMEAccountById(index: number, item: IACMEAccount) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-acme-order-heading" jhiTranslate="ca3SJhApp.acmeOrder.home.createOrEditLabel">Create or edit a Acme Order</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeOrder.orderId" for="field_orderId">Order Id</label>
                    <input type="number" class="form-control" name="orderId" id="field_orderId"
                           formControlName="orderId"/>
                    <div *ngIf="editForm.get('orderId').invalid && (editForm.get('orderId').dirty || editForm.get('orderId').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('orderId').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('orderId')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeOrder.status" for="field_status">Status</label>
                    <select class="form-control" name="status" formControlName="status" id="field_status">
                        <option value="Pending">{{'ca3SJhApp.OrderStatus.Pending' | translate}}</option>
                        <option value="Ready">{{'ca3SJhApp.OrderStatus.Ready' | translate}}</option>
                        <option value="Processing">{{'ca3SJhApp.OrderStatus.Processing' | translate}}</option>
                        <option value="Valid">{{'ca3SJhApp.OrderStatus.Valid' | translate}}</option>
                        <option value="Invalid">{{'ca3SJhApp.OrderStatus.Invalid' | translate}}</option>
                    </select>
                    <div *ngIf="editForm.get('status').invalid && (editForm.get('status').dirty || editForm.get('status').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('status').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeOrder.expires" for="field_expires">Expires</label>
                    <div class="input-group">
                        <input id="field_expires" type="text" class="form-control" name="expires" ngbDatepicker  #expiresDp="ngbDatepicker" formControlName="expires"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="expiresDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeOrder.notBefore" for="field_notBefore">Not Before</label>
                    <div class="input-group">
                        <input id="field_notBefore" type="text" class="form-control" name="notBefore" ngbDatepicker  #notBeforeDp="ngbDatepicker" formControlName="notBefore"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="notBeforeDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeOrder.notAfter" for="field_notAfter">Not After</label>
                    <div class="input-group">
                        <input id="field_notAfter" type="text" class="form-control" name="notAfter" ngbDatepicker  #notAfterDp="ngbDatepicker" formControlName="notAfter"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="notAfterDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeOrder.error" for="field_error">Error</label>
                    <input type="text" class="form-control" name="error" id="field_error"
                           formControlName="error"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeOrder.finalizeUrl" for="field_finalizeUrl">Finalize Url</label>
                    <input type="text" class="form-control" name="finalizeUrl" id="field_finalizeUrl"
                           formControlName="finalizeUrl"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeOrder.certificateUrl" for="field_certificateUrl">Certificate Url</label>
                    <input type="text" class="form-control" name="certificateUrl" id="field_certificateUrl"
                           formControlName="certificateUrl"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeOrder.csr" for="field_csr">Csr</label>
                    <select class="form-control" id="field_csr" name="csr" formControlName="csr">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="cSROption.id === editForm.get('csr').value?.id ? editForm.get('csr').value : cSROption" *ngFor="let cSROption of csrs; trackBy: trackCSRById">{{cSROption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeOrder.certificate" for="field_certificate">Certificate</label>
                    <select class="form-control" id="field_certificate" name="certificate" formControlName="certificate">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="certificateOption.id === editForm.get('certificate').value?.id ? editForm.get('certificate').value : certificateOption" *ngFor="let certificateOption of certificates; trackBy: trackCertificateById">{{certificateOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ca3SJhApp.acmeOrder.account" for="field_account">Account</label>
                    <select class="form-control" id="field_account" name="account" formControlName="account">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="aCMEAccountOption.id === editForm.get('account').value?.id ? editForm.get('account').value : aCMEAccountOption" *ngFor="let aCMEAccountOption of acmeaccounts; trackBy: trackACMEAccountById">{{aCMEAccountOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
